- platform: "mqtt"
  name: bathroom_water_0
  state_topic: "zigbee2mqtt/bathroom_water_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  qos: 1
  value_template: "{{ value_json.water_leak }}"
  device_class: "moisture"
  json_attributes:
    - "battery"
    - "voltage"
