- platform: "mqtt"
  name: hallway_pir_0
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: hallway_pir_1
  state_topic: "zigbee2mqtt/hallway_pir_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: hallway_smoke_0
  state_topic: "zigbee2mqtt/hallway_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.smoke }}"
  json_attributes: 
    - "battery"
    - "voltage"
