- platform: "mqtt"
  name: hallway_pir_0
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  json_attributes:
    - "battery"
    - "voltage"
    - "illuminance"
    - "linkquality"

- platform: "mqtt"
  name: livingroom_pir_0
  state_topic: "zigbee2mqtt/livingroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  json_attributes:
    - "battery"
    - "voltage"
    - "illuminance"
    - "linkquality"

- platform: "mqtt"
  name: upperhallway_pir_0
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  json_attributes:
    - "battery"
    - "voltage"
    - "illuminance"
    - "linkquality"

- platform: "mqtt"
  name: closetroom_pir_0
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  json_attributes:
    - "battery"
    - "voltage"
    - "illuminance"
    - "linkquality"

- platform: "mqtt"
  name: attichallway_pir_0
  state_topic: "zigbee2mqtt/attichallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  json_attributes:
    - "battery"
    - "voltage"
    - "illuminance"
    - "linkquality"

- platform: "mqtt"
  name: kitchen_pir_0
  state_topic: "zigbee2mqtt/kitchen_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  json_attributes:
    - "battery"
    - "voltage"
    - "illuminance"
    - "linkquality"

- platform: "mqtt"
  name: livingroom_smoke_0
  state_topic: "zigbee2mqtt/livingroom_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.smoke }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: scullery_smoke_0
  state_topic: "zigbee2mqtt/scullery_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.smoke }}"
  json_attributes:
    - "battery"
    - "voltage"
