- platform: template
  sensors:
    livingroom_humidity_too_low:
      entity_id:
        - sensor.livingroom_temp_0_humidity
        - input_number.livingroom_minimum_humidity
      value_template: >-
        {{ not is_state('sensor.livingroom_temp_0_humidity', 'unavailable') and states('sensor.livingroom_temp_0_humidity')|int < states('input_number.livingroom_minimum_humidity')|int }}
