- platform: template
  sensors:
    livingroom_dark:
      delay_off:
        minutes: 10
      value_template: >-
        {{ states('sensor.lux_livingroom')|default(0)|int <= states('input_number.livingroom_darkness_treshold')|int }}
