- platform: template
  sensors:
    movement:
      device_class: motion
      value_template: "{{ is_state('switch.movement', 'on') }}"
    door:
      device_class: opening
      value_template: "{{ is_state('switch.door', 'on') }}"
