- platform: template
  sensors:
    livingroom_planthealth_yucca_moisture:
      friendly_name: "Yucca water"
      value_template: "{{ states('sensor.livingroom_plant_yucca_moisture')|int > states('input_number.livingroom_plant_yucca_moisture_minimum')|int }}"
      icon_template: "{{ 'mdi:check-circle' if value else 'mdi:alert-circle' }}"

    livingroom_planthealth_yucca_conductivity:
      friendly_name: "Yucca voeding"
      value_template: "{{ states('sensor.livingroom_plant_yucca_conductivity')|int <= states('input_number.livingroom_plant_yucca_conductivity_minimum')|int }}"
      icon_template: "{{ 'mdi:check-circle' if value else 'mdi:alert-circle' }}"

    kitchen_planthealth_pancake_moisture:
      friendly_name: "Pannenkoekenplant water"
      value_template: "{{ states('sensor.kitchen_plant_pancake_moisture')|int <= states('input_number.kitchen_plant_pancake_moisture_minimum')|int }}"
      icon_template: "{{ 'mdi:check-circle' if value else 'mdi:alert-circle' }}"

    kitchen_planthealth_pancake_conductivity:
      friendly_name: "Pannenkoekenplant voeding"
      value_template: "{{ states('sensor.kitchen_plant_pancake_conductivity')|int <= states('input_number.kitchen_plant_pancake_conductivity_minimum')|int }}"
      icon_template: "{{ 'mdi:check-circle' if value else 'mdi:alert-circle' }}"