- platform: template
  sensors:
    frank_home_direction:
      friendly_name: "Frank richting Home"
      value_template: "{{ state_attr('sensor.proximity_frank_home_stats_mean', 'change') | float < -0.5 }}"
      delay_on:
        minutes: 5
      delay_off:
        minutes: 15
    malissa_home_direction:
      friendly_name: "Malissa richting Home"
      value_template: "{{ state_attr('sensor.proximity_malissa_home_stats_mean', 'change') | float < -0.5 }}"
      delay_on:
        minutes: 5
      delay_off:
        minutes: 15
