image: python:3

before_script:
  - git clone --single-branch --branch master https://github.com/home-assistant/home-assistant/ /hass
  - cd /hass
  - python -m venv venv
  - source venv/bin/activate
  - script/setup
  - python -V
  - hass --version
  - mv "${CI_PROJECT_DIR}/secrets-empty.yaml" "${CI_PROJECT_DIR}/secrets.yaml"

test:
  script:
  - hass -c "${CI_PROJECT_DIR}" --script check_config
