language: minimal

services:
  - docker

before_install:
  - docker pull homeassistant/homeassistant:latest
  - docker run homeassistant/homeassistant:latest python -m homeassistant --version
  - docker run homeassistant/homeassistant:latest python --version
  - mv secrets-empty.yaml secrets.yaml

script:
  - docker run -v "${TRAVIS_BUILD_DIR}:/hassconfig" homeassistant/homeassistant:latest python -m homeassistant --script check_config -c /hassconfig
