homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

# Enables the frontend
frontend: !include themes.yaml

# Enables configuration UI
config:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

recorder:
  db_url: !secret recorder_db_url

# Text to speech
tts:
  - platform: google

light: !include lights.yaml
group: !include_dir_merge_named groups
# script: !include_dir_list scripts
# automation: !include_dir_list automations
