homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: metric
  time_zone: !secret time_zone
  customize_domain:
    light:
      assumed_state: false
  whitelist_external_dirs:
    - "/tmp"
    - !secret dahua_folder_0

system_health:

hassio:

zeroconf:

map:

updater:
  reporting: false

person:
  - name: Malissa
    id: malissa
    device_trackers:
      - device_tracker.malissa_router
      - device_tracker.malissa_gps
  - name: Frank
    id: frank
    device_trackers:
      - device_tracker.frank_router
      - device_tracker.frank_gps

# google_assistant:
#   project_id: !secret google_assistant_project_id
#   api_key: !secret google_assistant_homegraph_api_key
#   expose_by_default: false
#   # exposed_domains:
#   #   - light
#   entity_config:
#     light.livingroom_lights:
#       name: De Woonkamer Lampen
#       expose: true
#     light.hallway_lights:
#       name: De Gang Lamp
#       expose: true
#     light.closetroom_lights:
#       name: De Kastenkamer Lamp
#       expose: true
#     light.upperhallway_light_0:
#       name: De Overloop Lamp
#       expose: true
#     light.attichallway_light_0:
#       name: De Zolder Lamp
#       expose: true
#     light.kitchen_lights:
#       name: De Keuken Lamp
#       expose: true
#     # script.closetroom_heating_on:
#     #   name: De Kastenkamerverwarming
#     #   expose: true
#     # script.bathroom_heating_on:
#     #   name: De Badkamerverwarming
#     #   expose: true

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

apcupsd:
  host: !secret apcupsd_host

zigbee2mqtt_networkmap:

emulated_hue:
  exposed_domains:
    - script
    - scene

http:
  # api_password: !secret api_password
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret http_trusted_proxy_0
  ip_ban_enabled: true
  login_attempts_threshold: 3

#calendar
google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

logger:
  default: error
#   logs:
    # homeassistant.components.homekit_controller: debug
    # homeassistant.components.tado: info

# Enables configuration UI
config:

# Discover some devices automatically
discovery:

mobile_app:

# Track the sun
sun:

# rflink:
#   port: !secret rflink_gateway_dev_path

recorder:
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - scene
      - script

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  include:
    entities:
      - binary_sensor.frank_home_direction
      - binary_sensor.malissa_home_direction
      - sun.sun
      - light.kitchen_lights
      - light.hallway_lights
      - light.attichallway_lights
      - light.livingroom_lights
      - light.upperhallway_lights
      - light.closetroom_lights
      - sensor.doorbell
      - binary_sensor.livingroom_planthealth_yucca_moisture
      - binary_sensor.kitchen_planthealth_pancake_moisture
      - input_number.bathroom_fan_speed
    domains:
      - person
      - media_player
      - remote
      - input_text

# Text to speech
tts:
  - platform: google_translate

input_boolean: !include_dir_merge_named components/input_booleans
input_number: !include_dir_merge_named components/input_numbers
input_datetime: !include_dir_merge_named components/input_datetimes
input_text: !include_dir_merge_named components/input_texts
input_select: !include_dir_merge_named components/input_selects

# alert: !include_dir_merge_named components/alerts
light: !include_dir_merge_list components/lights
sensor: !include_dir_merge_list components/sensors
switch: !include_dir_merge_list components/switches
binary_sensor: !include_dir_merge_list components/binary_sensors
scene: !include_dir_merge_list scenes
group: !include groups.yaml
automation: !include_dir_merge_list automations
shell_command: !include_dir_merge_named components/shell_commands
notify: !include_dir_merge_list components/notifiers
media_player: !include_dir_merge_list components/media_players
script: !include scripts.yaml
timer: !include_dir_merge_named components/timers
history_graph: !include_dir_merge_named components/history_graphs
zone: !include_dir_merge_list components/zones
proximity: !include_dir_merge_named components/proximities
plant: !include_dir_merge_named components/plants

folder_watcher:
  - folder: !secret dahua_folder_0
    patterns:
      - '*.jpg'

remote:
  - platform: harmony
    name: livingroom
    host: !secret harmony_livingroom_ip

device_tracker:
  - platform: nmap_tracker
    hosts: !secret nmap_tracker_hosts
    home_interval: 5
    interval_seconds: 30
    consider_home: 00:05:00
    scan_options: " --privileged --host-timeout 5s -sP "
    new_device_defaults:
      track_new_devices: false
  # - platform: google_maps
  #   username: !secret google_maps_devicetracker_user
  #   password: !secret google_maps_devicetracker_password
  #   new_device_defaults:
  #     track_new_devices: true

camera:
  - platform: mjpeg
    name: !secret cam1_name
    mjpeg_url: !secret cam1_input
  - platform: mjpeg
    name: !secret cam2_name
    mjpeg_url: !secret cam2_input
    username: !secret cam2_username
    password: !secret cam2_password
    authentication: digest
  # - platform: mjpeg
  #   name: !secret cam3_name
  #   mjpeg_url: !secret cam3_input
  #   still_image_url: !secret cam3_input_still
  # - platform: onvif
  #   name: !secret cam4_name
  #   host: !secret cam4_ip
  #   profile: 2
  #   port: 80
  #   username: !secret cam2_username
  #   password: !secret cam2_password

ffmpeg:

weather:
  - platform: buienradar
    name: home

mqtt:
  discovery: false
  # discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  broker: !secret mqtt_server

tado:
  username: !secret tado_username
  password: !secret tado_password

xiaomi_aqara:
  gateways:
    - host: !secret aqara_gateway_ip
      key: !secret aqara_gateway_key

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 5
  tags_attributes:
    - friendly_name
    - entity_id
  component_config_glob:
    'sensor.*_temperature':
      override_measurement: 'temperature'
    'sensor.*_humidity':
      override_measurement: 'humidity'
    'sensor.*_linkquality':
      override_measurement: 'linkquality'
    'sensor.*_battery':
      override_measurement: 'battery'
    'sensor.*_heating':
      override_measurement: 'heating'
    'sensor.*_illuminance':
      override_measurement: 'illuminance'
    'sensor.trash_*':
      override_measurement: 'trash'
    'sensor.ups_*':
      override_measurement: 'ups'
    'sensor.waze_*':
      override_measurement: 'waze'
    'sensor.*_link':
      override_measurement: 'link'
    'sensor.*_dark':
      override_measurement: 'dark'
  component_config_domain:
    'climate':
      override_measurement: 'climate'

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_frank_id
      - !secret telegram_malissa_id

webostv:
  host: !secret tv_livingroom_ip
  name: livingroom_tv
