homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
   # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize_domain:
    light:
      assumed_state: false

system_health:

hassio:

map:

updater:
  reporting: false

# mysensors:
#   gateways:
#     - device: !secret mysensors_gateway
#       tcp_port: 5003
#       persistence_file: !secret mysensors_persistence_file
#   persistence: true
#   version: '2.0'

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_homegraph_api_key
  expose_by_default: false
  # exposed_domains:
  #   - light
  entity_config:
    light.livingroom_lights:
      name: De Woonkamer Lampen
      expose: true
    light.hallway_lights:
      name: De Gang Lamp
      expose: true
    light.closetroom_lights:
      name: De Kastenkamer Lamp
      expose: true
    light.upperhallway_light_0:
      name: De Overloop Lamp
      expose: true
    light.attichallway_light_0:
      name: De Zolder Lamp
      expose: true
    light.kitchen_lights:
      name: De Keuken Lamp
      expose: true
    script.closetroom_heating_on:
      name: De Kastenkamerverwarming
      expose: true
    script.bathroom_heating_on:
      name: De Badkamerverwarming
      expose: true

# Enables the frontend
frontend:

apcupsd:
  host: !secret apcupsd_host

zigbee2mqtt_networkmap:

# panel_iframe:
#    networkmap:
#      title: 'Zigbee Map'
#      url: '/local/zigbee2mqtt_networkmap/map.html'
#      icon: 'mdi:graphql'

emulated_hue:
  exposed_domains:
    - script
    - scene

http:
  # api_password: !secret api_password
  # base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret http_trusted_proxy_0
  ip_ban_enabled: true
  login_attempts_threshold: 3

logger:
  default: warning
  logs:
    homeassistant.components.homekit_controller: debug
    homeassistant.components.climate.tado: debug

# Enables configuration UI
config:

# Discover some devices automatically
discovery:
  enable:
    - homekit

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# rflink:
#   port: /dev/ttyACM0

recorder:
#  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - scene
      - script

# Text to speech
tts:
  - platform: google

input_number: !include_dir_merge_named components/input_numbers
input_datetime: !include_dir_merge_named components/input_datetimes
input_text: !include_dir_merge_named components/input_texts
input_select: !include_dir_merge_named components/input_selects

light: !include_dir_merge_list components/lights
sensor: !include_dir_merge_list components/sensors
switch: !include_dir_merge_list components/switches
binary_sensor: !include_dir_merge_list components/binary_sensors
scene: !include_dir_merge_list scenes
group: !include groups.yaml
automation: !include_dir_merge_list automations
shell_command: !include_dir_merge_named components/shell_commands
notify: !include_dir_merge_list components/notifiers
media_player: !include_dir_merge_list components/media_players
script: !include scripts.yaml
timer: !include_dir_merge_named components/timers
history_graph: !include_dir_merge_named components/history_graphs
zone: !include_dir_merge_list components/zones
proximity: !include_dir_merge_named components/proximities

# remote:
#   - platform: harmony
#     name: livingroom
#     host: !secret harmony_livingroom_ip

device_tracker:
  - platform: nmap_tracker
    hosts: !secret nmap_tracker_hosts
    home_interval: 5
    interval_seconds: 30
    consider_home: 00:30:00
    scan_options: " --privileged --host-timeout 5s -sP "
    new_device_defaults:
      track_new_devices: false
  # - platform: google_maps
  #   username: !secret google_maps_devicetracker_user
  #   password: !secret google_maps_devicetracker_password
  #   new_device_defaults:
  #     track_new_devices: true

camera:
  - platform: mjpeg
    name: !secret cam1_name
    mjpeg_url: !secret cam1_input

# ffmpeg:

mqtt:
  discovery: false
  # discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  broker: !secret mqtt_server

tado:
  username: !secret tado_username
  password: !secret tado_password

# utility_meter:
#   daily_energy:
#     source: sensor.main_power_usage
#     cycle: daily
#   weekly_energy:
#     source: sensor.main_power_usage
#     cycle: weekly
#   monthly_energy:
#     source: sensor.main_power_usage
#     cycle: monthly

xiaomi_aqara:
  gateways:
    - host: !secret aqara_gateway_ip
      key: !secret aqara_gateway_key

influxdb:
  host: !secret influxdb_host
  max_retries: 5
  tags_attributes:
    - friendly_name
    - entity_id
