homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  customize_domain:
    light:
      assumed_state: false

mysensors:
  gateways:
    - device: !secret mysensors_gateway
      tcp_port: 5003
      persistence_file: !secret mysensors_persistence_file
  persistence: true
  version: '2.0'

# Enables the frontend
frontend:

emulated_hue:
  exposed_domains:
    - script
    - scene

http:
  api_password: !secret api_password
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3

logger:
  default: warn

# Enables configuration UI
config:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

rflink:
  port: /dev/ttyACM0

ios:

# weather:
#   - platform: yweather
#     name: "Yahoo Weather"

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - scene

# Text to speech
tts:
  - platform: google

# does not work in components/input_selects
input_select:
  timeofday:
    name: Time of day
    # initial: evening
    options:
      - "morning"
      - "midday"
      - "evening"
      - "night"

input_number:
  hallway_timeout_morning:
    min: 10
    max: 300
    step: 10
    unit_of_measurement: sec
  hallway_timeout_midday:
    min: 10
    max: 300
    step: 10
    unit_of_measurement: sec
  hallway_timeout_evening:
    min: 10
    max: 300
    step: 10
    unit_of_measurement: sec
  hallway_timeout_night:
    min: 10
    max: 300
    step: 10
    unit_of_measurement: sec
  hallway_timeout_full:
    min: 60
    max: 600
    step: 10
    unit_of_measurement: sec
  upperhallway_timeout_morning:
    min: 10
    max: 300
    step: 10
    unit_of_measurement: sec
  upperhallway_timeout_midday:
    min: 10
    max: 300
    step: 10
    unit_of_measurement: sec
  upperhallway_timeout_evening:
    min: 10
    max: 300
    step: 10
    unit_of_measurement: sec
  upperhallway_timeout_night:
    min: 10
    max: 300
    step: 10
    unit_of_measurement: sec
  upperhallway_timeout_full:
    min: 120
    max: 600
    step: 10
    unit_of_measurement: sec
  upperhallway_recent_motions_treshold:
    min: 1
    max: 10
    step: 1
  upperhallway_recent_motions_seconds:
    min: 1
    max: 120
    step: 1
    unit_of_measurement: sec
  hallway_brightness_morning:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  hallway_brightness_midday:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  hallway_brightness_evening:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  hallway_brightness_night:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  hallway_brightness_full:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  upperhallway_brightness_morning:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  upperhallway_brightness_midday:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  upperhallway_brightness_evening:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  upperhallway_brightness_night:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  upperhallway_brightness_full:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  livingroom_brightness_morning:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  livingroom_brightness_midday:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  livingroom_brightness_evening:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  livingroom_brightness_night:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  livingroom_brightness_full:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  livingroom_darkness_treshold:
    min: 0
    max: 1000
    step: 50
    unit_of_measurement: 'lx'
  hallway_darkness_treshold:
    min: 0
    max: 1000
    step: 50
    unit_of_measurement: 'lx'
  upperhallway_darkness_treshold:
    min: 0
    max: 1000
    step: 50
    unit_of_measurement: 'lx'

input_datetime:
  trash_announcement_time:
    has_time: true

input_text:
  trash_announcement_zipcode: {}
  trash_announcement_housenumber: {}  

light: !include_dir_merge_list components/lights
sensor: !include_dir_merge_list components/sensors
switch: !include_dir_merge_list components/switches
binary_sensor: !include_dir_merge_list components/binary_sensors
scene: !include_dir_merge_list scenes
group: !include groups.yaml
automation: !include_dir_merge_list automations
shell_command: !include_dir_merge_named components/shell_commands
notify: !include_dir_merge_list components/notifiers
media_player: !include_dir_merge_list components/media_players
script: !include scripts.yaml
timer: !include_dir_merge_named components/timers
history_graph: !include_dir_merge_named components/history_graphs


remote:
  - platform: harmony
    name: livingroom
    host: !secret harmony_livingroom_ip

device_tracker:
  - platform: nmap_tracker
    hosts: !secret nmap_tracker_hosts
    home_interval: 10
    interval_seconds: 30
    consider_home: 00:20:00
    scan_options: " --host-timeout 5s --privileged -sP "
    new_device_defaults:
      track_new_devices: false

# camera:
#   - platform: ffmpeg
#     name: !secret cam1_name
#     input: !secret cam1_input

ffmpeg:
  ffmpeg_bin: /usr/local/bin/ffmpeg

mqtt:
  broker: !secret mqtt_server

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_frank_id
      - !secret telegram_malissa_id
      - !secret telegram_harrie_id
