homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
   # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize_domain:
    light:
      assumed_state: false

map:

mysensors:
  gateways:
    - device: !secret mysensors_gateway
      tcp_port: 5003
      persistence_file: !secret mysensors_persistence_file
  persistence: true
  version: '2.0'

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_assistant_homegraph_api_key
  agent_user_id: !secret google_assistant_agent_user_id
  exposed_by_default: false
  exposed_domains:
    - group
    - light
  entity_config:
    group.milights:
      expose: true
      name: Alle lampen
      aliases:
        - "all lights"
    group.livingroom_lights:
      name: woonkamer lampen
      expose: true
      aliases:
        - "livingroom lights"
    group.hallway_lights:
      name: gang lampen
      expose: true
      aliases:
        - "hallway lights"
    group.upperhallway_lights:
      name: overloop lampen
      aliases:
        - "upperhallway lights"
      expose: true

# Enables the frontend
frontend:

apcupsd:
  host: !secret apcupsd_host

emulated_hue:
  exposed_domains:
    - script
    - scene

http:
  api_password: !secret api_password
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3

logger:
  default: warn

# Enables configuration UI
config:

# Discover some devices automatically
# discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

rflink:
  port: /dev/ttyACM0

ios:

# weather:
#   - platform: yweather
#     name: "Yahoo Weather"

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - scene

# Text to speech
tts:
  - platform: google

input_number: !include_dir_merge_named components/input_numbers
input_datetime: !include_dir_merge_named components/input_datetimes
input_text: !include_dir_merge_named components/input_texts
input_select: !include_dir_merge_named components/input_selects

light: !include_dir_merge_list components/lights
sensor: !include_dir_merge_list components/sensors
switch: !include_dir_merge_list components/switches
binary_sensor: !include_dir_merge_list components/binary_sensors
scene: !include_dir_merge_list scenes
group: !include groups.yaml
automation: !include_dir_merge_list automations
shell_command: !include_dir_merge_named components/shell_commands
notify: !include_dir_merge_list components/notifiers
media_player: !include_dir_merge_list components/media_players
script: !include scripts.yaml
timer: !include_dir_merge_named components/timers
history_graph: !include_dir_merge_named components/history_graphs
zone: !include_dir_merge_list components/zones
proximity: !include_dir_merge_named components/proximities

remote:
  - platform: harmony
    name: livingroom
    host: !secret harmony_livingroom_ip

device_tracker:
  - platform: nmap_tracker
    hosts: !secret nmap_tracker_hosts
    home_interval: 10
    interval_seconds: 30
    consider_home: 00:20:00
    scan_options: " --host-timeout 5s --privileged -sP "
    new_device_defaults:
      track_new_devices: false
  - platform: google_maps
    username: !secret google_maps_devicetracker_user
    password: !secret google_maps_devicetracker_password
    new_device_defaults:
      track_new_devices: true

# camera:
#   - platform: ffmpeg
#     name: !secret cam1_name
#     input: !secret cam1_input

ffmpeg:
  ffmpeg_bin: /usr/local/bin/ffmpeg

mqtt:
  # discovery: true
  # discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  broker: !secret mqtt_server

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_frank_id
      - !secret telegram_malissa_id
      - !secret telegram_harrie_id
