- platform: template
  switches:
    livingroom_tv_input_chromecast:
      value_template: "{{ is_state_attr('remote.livingroom', 'current_activity', 'Chromecast') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.livingroom
          activity: 'Chromecast'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.livingroom

    livingroom_tv_input_cable:
      value_template: "{{ is_state_attr('remote.livingroom', 'current_activity', 'TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.livingroom
          activity: 'TV'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.livingroom

    livingroom_tv_input_ps4:
      value_template: "{{ is_state_attr('remote.livingroom', 'current_activity', 'PS4') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.livingroom
          activity: 'PS4'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.livingroom

    livingroom_tv_input_music:
      value_template: "{{ is_state_attr('remote.livingroom', 'current_activity', 'Music') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.livingroom
          activity: 'Music'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.livingroom
