- platform: mqtt
  name: zigbee2mqtt_permit_join
  state_topic: "zigbee2mqtt/bridge/config/permit_join"
  command_topic: "zigbee2mqtt/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"
  optimistic: false
  qos: 0
  retain: true

- platform: "mqtt"
  name: garage_power_0
  state_topic: "zigbee2mqtt/garage_power_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  qos: 1
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/garage_power_0/set"

- platform: "mqtt"
  name: bathroom_fan_0
  state_topic: !secret bathroom_fan_mqtt_state_topic
  # availability_topic: !secret bathroom_fan_mqtt_availability_topic
  payload_off: "off"
  payload_on: "on"
  qos: 1
  command_topic: !secret bathroom_fan_mqtt_command_topic
