- platform: rflink
  devices:
    # !secret hallway_pir_0_id:
    #   name: hallway_pir_0
    # !secret hallway_pir_1_id:
    #   name: hallway_pir_1
    !secret upperhallway_pir_0_id:
      name: upperhallway_pir_0
    !secret upperhallway_pir_1_id:
      name: upperhallway_pir_1
    !secret hallway_door_0_id:
      name: hallway_door_0
    !secret hallway_switch_0_id:
      name: hallway_switch_0
    !secret hallway_switch_1_id:
      name: hallway_switch_1
    !secret chromecast_livingroom_power_id:
      name: chromecast_livingroom_power
