# - alias: "Stuur bericht bij beweging maar niemand is thuis"
#   initial_state: off
#   trigger:
#     - platform: state
#       entity_id:
#         switch.upper_hallway_pir_0,
#         switch.upper_hallway_pir_1,
#         switch.hallway_pir_0,
#         switch.hallway_pir_1,
#         switch.hallway_door_0
#       to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: "{{ is_state('group.all_persons', 'not_home') }}"
#   action:
#     service: notify.frank
#     data_template:
#       title: "*ALARM: {{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].attributes.friendly_name }}*"
#       message: "Onverwachte activiteit gedetecteerd!"


- alias: "Stuur bericht bij achterdeur open"
  trigger:
    - platform: state
      entity_id:
        binary_sensor.kitchen_door_0
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{{ not is_state('input_text.last_motion', 'Woonkamer PIR') and not is_state('input_text.last_motion', 'Keuken PIR')}}"
      - condition: state
        entity_id: group.all_persons
        state: 'not_home'
  action:
    - service: notify.telegram
      data_template:
        title: "Deur geopend"
        message: "De achterdeur is geopend"

- alias: "Geluid bij achterdeur open"
  trigger:
    - platform: state
      entity_id:
        binary_sensor.kitchen_door_0
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.timeofday
        state: midday
      - condition: template
        value_template: "{{ not is_state('input_text.last_motion', 'Woonkamer PIR') and not is_state('input_text.last_motion', 'Keuken PIR')}}"
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 10001
        ringtone_vol: 100

- alias: "Stuur bericht bij brand"
  trigger:
    - platform: state
      entity_id:
        binary_sensor.livingroom_smoke_0,
        binary_sensor.scullery_smoke_0
      to: 'on'
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.bathroom_fan_speed
        value: "2"
    - service: notify.telegram
      data_template:
        title: "ROOKALARM: {{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].attributes.friendly_name }}"
        message: "Rook gedetecteerd!"
    - service: light.turn_on
      data:
        entity_id: !secret aqara_gateway_light
        brightness_pct: 100
        color_name: red
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
