# - alias: "Stuur bericht bij beweging maar niemand is thuis"
#   initial_state: off
#   trigger:
#     - platform: state
#       entity_id:
#         switch.upper_hallway_pir_0,
#         switch.upper_hallway_pir_1,
#         switch.hallway_pir_0,
#         switch.hallway_pir_1,
#         switch.hallway_door_0
#       to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: "{{ is_state('group.all_devices', 'not_home') }}"
#   action:
#     service: notify.frank
#     data_template:
#       title: "*ALARM: {{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].attributes.friendly_name }}*"
#       message: "Onverwachte activiteit gedetecteerd!"

- alias: "Stuur bericht bij brand"
  initial_state: off
  trigger:
    - platform: state
      entity_id:
        binary_sensor.livingroom_smoke_0,
        binary_sensor.attichallway_smoke_0
      to: 'on'
  action:
    service: notify.web
    data_template:
      title: "*ALARM: {{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].attributes.friendly_name }}*"
      message: "Rook gedetecteerd!"
