# - alias: "Stuur bericht bij beweging maar niemand is thuis"
#   initial_state: off
#   trigger:
#     - platform: state
#       entity_id:
#         switch.upper_hallway_pir_0,
#         switch.upper_hallway_pir_1,
#         switch.hallway_pir_0,
#         switch.hallway_pir_1,
#         switch.hallway_door_0
#       to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: "{{ is_state('group.all_devices', 'not_home') }}"
#   action:
#     service: notify.frank
#     data_template:
#       title: "*ALARM: {{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].attributes.friendly_name }}*"
#       message: "Onverwachte activiteit gedetecteerd!"


- alias: "Stuur bericht bij achterdeur open"
  trigger:
    - platform: state
      entity_id:
        sensor.kitchen_door_0
      from: 'closed'
      to: 'open'
  action:
    - service: notify.web
      data_template:
        title: "Deur geopend"
        message: "De achterdeur is geopend"
        data:
          tag: "backdooropen-0-notification"
          renotify: true

- alias: "Geluid bij achterdeur open"
  trigger:
    - platform: state
      entity_id:
        sensor.kitchen_door_0
      from: 'closed'
      to: 'open'
  condition:
    condition: template
    value_template: "{{ is_state('input_select.timeofday', 'midday') }}"
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 10001
        ringtone_vol: 100

- alias: "Stuur bericht bij brand"
  trigger:
    - platform: state
      entity_id:
        sensor.livingroom_smoke_0,
        sensor.scullery_smoke_0
      to: 'on'
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.bathroom_fan_speed
        value: "2"
    - service: notify.web
      data_template:
        title: "ROOKALARM: {{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].attributes.friendly_name }}"
        message: "Rook gedetecteerd!"
    - service: light.turn_on
      data:
        entity_id: !secret aqara_gateway_light
        brightness_pct: 100
        color_name: red
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
    - delay:
        seconds: 10
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2
        ringtone_vol: 100
