- alias: "badkamer fan start slow humidity"
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_humidity_rising
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_number.bathroom_fan_last_on_humidity', '0.0') }}"
      - condition: template
        value_template: "{{ not is_state('input_number.bathroom_fan_speed', '2.0') }}"
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bathroom_fan_last_on_humidity
        value: "{{ state_attr('sensor.bathroom_humidity_stats_mean', 'min_value') | int }}"
    - service: input_number.set_value
      data:
        entity_id: input_number.bathroom_fan_speed
        value: "1"

- alias: "badkamer fan delayed high humidity"
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_humidity_rising
      from: "off"
      to: "on"
      for:
        minutes: 15
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ not is_state('input_number.bathroom_fan_last_on_humidity', '0.0') }}"
      - condition: template
        value_template: "{{ not is_state('input_number.bathroom_fan_speed', '0.0') }}"
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.bathroom_fan_speed
      value: "2"

- alias: "badkamer fan stop"
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_humidity_normal
      from: "off"
      to: "on"
      for:
        seconds: 10
  condition:
    condition: template
    value_template: "{{ is_state('binary_sensor.toilet_occupied', 'off') }}"
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.bathroom_fan_last_on_humidity
        value: "0"
    - service: input_number.set_value
      data:
        entity_id: input_number.bathroom_fan_speed
        value: "0"

- alias: "toilet fan start"
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_occupied
      from: "off"
      to: "on"
      for:
        seconds: 10
  condition:
    condition: template
    value_template: "{{ is_state('input_number.bathroom_fan_last_on_humidity', '0.0') }}"
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.bathroom_fan_speed
        value: "1"

- alias: "toilet fan start high"
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_occupied
      from: "on"
      to: "off"
      for:
        seconds: 30
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_number.bathroom_fan_last_on_humidity', '0.0') }}"
      - condition: template
        value_template: "{{ is_state('input_number.bathroom_fan_speed', '1.0') }}"
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.bathroom_fan_speed
        value: "2"

- alias: "toilet fan stop"
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_occupied
      from: "on"
      to: "off"
  condition:
    condition: template
    value_template: "{{ is_state('binary_sensor.bathroom_humidity_normal', 'on') }}"
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.bathroom_fan_last_on_humidity
        value: "0"
    - service: input_number.set_value
      data:
        entity_id: input_number.bathroom_fan_speed
        value: "0"

- alias: "Sonoff Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/state"
        payload: ""

- alias: "badkamer fan off input_number"
  trigger:
    - platform: numeric_state
      entity_id: input_number.bathroom_fan_speed
      below: 1
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bathroom_fan_low
    - service: switch.turn_off
      data:
        entity_id: switch.bathroom_fan_high

- alias: "badkamer fan low input_number"
  trigger:
    - platform: numeric_state
      entity_id: input_number.bathroom_fan_speed
      below: 2
      above: 0
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bathroom_fan_high
    - service: switch.turn_on
      data:
        entity_id: switch.bathroom_fan_low

- alias: "badkamer fan high input_number"
  trigger:
    - platform: numeric_state
      entity_id: input_number.bathroom_fan_speed
      above: 1
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bathroom_fan_low
    - service: switch.turn_on
      data:
        entity_id: switch.bathroom_fan_high
