- alias: "TV uit als chromecast 15 minuten idle is"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_tv
      to: 'idle'
      for:
        minutes: 15
    - platform: state
      entity_id: media_player.woonkamer_tv
      to: 'off'
      for:
        minutes: 15
  condition:
    condition: template
    value_template: "{{ is_state_attr('remote.livingroom', 'current_activity', 'Chromecast') }}"
  action:
    - service: remote.turn_off
      data:
        entity_id: remote.livingroom

- alias: "Notify dat TV uit gaat over 2 minuten geen beweging"
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_pir_0
      to: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: binary_sensor.livingroom_pir_0
      to: 'off'
      for:
        minutes: 2
    - platform: state
      entity_id: binary_sensor.livingroom_pir_0
      to: 'off'
      for:
        minutes: 55
    - platform: state
      entity_id: binary_sensor.livingroom_pir_0
      to: 'off'
      for:
        minutes: 56
    - platform: state
      entity_id: binary_sensor.livingroom_pir_0
      to: 'off'
      for:
        minutes: 57
    - platform: state
      entity_id: binary_sensor.livingroom_pir_0
      to: 'off'
      for:
        minutes: 58
    - platform: state
      entity_id: binary_sensor.livingroom_pir_0
      to: 'off'
      for:
        minutes: 59
  condition:
    condition: template
    value_template: "{{ not is_state_attr('remote.livingroom', 'current_activity', 'PowerOff') }}"
  action:
    - service: notify.livingroom_tv
      data_template:
        message: "Geen beweging gedetecteerd. Over {{ 60 - (trigger.for.seconds|int/60)|int }} {% if trigger.for.seconds/60|int == 59 -%}minuut{%- else -%}minuten{%- endif %} wordt de TV uitgeschakeld."

- alias: "TV uit als er een uur geen beweging in de woonkamer is"
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_pir_0
      to: 'off'
      for:
        minutes: 60
  condition:
    condition: template
    value_template: "{{ not is_state_attr('remote.livingroom', 'current_activity', 'PowerOff') }}"
  action:
    - service: remote.turn_off
      data:
        entity_id: remote.livingroom

# - alias: "Greet when someone gets home and the google home is not used"
#   initial_state: off
#   trigger:
#     - platform: state
#       entity_id: person.frank
#       to: 'home'
#     - platform: state
#       entity_id: person.malissa
#       to: 'home'
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: "{{ not is_state('input_select.timeofday', 'night') }}"
#       - condition: state
#         entity_id: !secret google_home_woonkamer_entity_id
#         state: 'off'
#   action:
#     - service: media_player.volume_set
#       data:
#         entity_id: !secret google_home_woonkamer_entity_id
#         volume_level: 0.7
#     - service: tts.google_say
#       entity_id: !secret google_home_woonkamer_entity_id
#       data_template:
#         message: "Aankomstmelding, {{ states.device_tracker[trigger.entity_id.split('.')[1]].attributes.friendly_name }} komt thuis."
#         language: 'nl'
#     - service: media_player.turn_off
#       data:
#         entity_id: !secret google_home_woonkamer_entity_id

# - alias: "Announce trash today when person passes motion first in morning"
#   trigger:
#     - platform: state
#       entity_id:
#         switch.livingroom_pir_0
#       to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: '{{ is_state("input_select.timeofday", "morning") }}'
#       - condition: template
#         value_template: '{{ states.remote.livingroom.attributes.current_activity == "PowerOff" }}'
#       - condition: template
#         value_template: '{{ not is_state("sensor.trash_today", None) }}'
#   action:
#     - service: media_player.turn_on
#       entity_id: media_player.woonkamer_tv
#     - service: remote.turn_on
#       data:
#         entity_id: remote.livingroom
#         activity: "Chromecast luisteren"
#     # - delay: "00:00:05"
#     - service: tts.google_say
#       entity_id: media_player.woonkamer_tv
#       data_template:
#         message: "Goedemorgen. Vandaag moet er afval aan de straat worden gezet, namelijk: {{ states('sensor.trash_today') }}."
#         language: 'nl'
#     - delay: "00:00:20"
#     - service: media_player.turn_off
#       entity_id: media_player.woonkamer_tv
#     - service: remote.turn_off
#       data:
#         entity_id: remote.livingroom

# # - alias: "Turn on audio when somebody connects spotify to chromecast and TV is powered off"
# #   initial_state: on
# #   trigger:
# #     - platform: state
# #       entity_id: media_player.woonkamer_tv
# #       from: 'idle'
# #       to: 'playing'
# #     - platform: state
# #       entity_id: media_player.woonkamer_tv
# #       from: 'idle'
# #       to: 'paused'
# #     - platform: state
# #       entity_id: media_player.woonkamer_tv
# #       from: 'off'
# #       to: 'playing'
# #     - platform: state
# #       entity_id: media_player.woonkamer_tv
# #       from: 'off'
# #       to: 'paused'
# #   condition:
# #     condition: and
# #     conditions:
# #       - condition: template
# #         value_template: '{{ states.remote.livingroom.attributes.current_activity == "PowerOff" }}'
# #       - condition: template
# #         value_template: '{{ trigger.to_state.attributes.app_name == "Spotify" }}'
# #   action:
# #     - service: remote.turn_on
# #       data:
# #         entity_id: remote.livingroom
# #         activity: "Chromecast luisteren"

# # - alias: "Turn off audio when somebody disconnects spotify to chromecast and audio is turned on"
# #   initial_state: on
# #   trigger:
# #     - platform: state
# #       entity_id: media_player.woonkamer_tv
# #       from: 'playing'
# #       to: 'idle'
# #     - platform: state
# #       entity_id: media_player.woonkamer_tv
# #       from: 'paused'
# #       to: 'idle'
# #     - platform: state
# #       entity_id: media_player.woonkamer_tv
# #       from: 'playing'
# #       to: 'off'
# #     - platform: state
# #       entity_id: media_player.woonkamer_tv
# #       from: 'paused'
# #       to: 'off'
# #   condition:
# #     condition: and
# #     conditions:
# #       - condition: template
# #         value_template: '{{ states.remote.livingroom.attributes.current_activity == "Chromecast luisteren" }}'
# #       - condition: template
# #         value_template: '{{ trigger.from_state.attributes.app_name == "Spotify" }}'
# #       - condition: template
# #         value_template: '{{ trigger.to_state.attributes.app_name == null }}'
# #   action:
# #     - service: remote.turn_off
# #       data:
# #         entity_id: remote.livingroom

