# - alias: "Stuur bericht bij beweging maar niemand is thuis"
#   initial_state: off
#   trigger:
#     - platform: state
#       entity_id:
#         switch.upper_hallway_pir_0,
#         switch.upper_hallway_pir_1,
#         switch.hallway_pir_0,
#         switch.hallway_pir_1,
#         switch.hallway_door_0
#       to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: "{{ is_state('group.all_persons', 'not_home') }}"
#   action:
#     service: notify.frank
#     data_template:
#       title: "*ALARM: {{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].attributes.friendly_name }}*"
#       message: "Onverwachte activiteit gedetecteerd!"
- alias: "Ganglicht bij aanbellen voordeur"
  trigger:
    - platform: state
      entity_id: sensor.doorbell
      from: 'not_pressed'
      to: 'pressed'
  condition:
    condition: template
    value_template: "{{ is_state('input_select.timeofday', 'evening') }}"
  action:
    - delay:
        seconds: 10
    - service: light.turn_on
      data:
        entity_id: light.hallway_lights

- alias: "Stuur bericht bij activiteit voordeur"
  trigger:
    - platform: event
      event_type: dahua_event_received
      event_data:
        code: CrossLineDetection
        action: Start
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.voortuin
        filename: "/tmp/last_activity_frontdoor.jpg"
    - service: telegram_bot.send_photo
      data:
        file: "/tmp/last_activity_frontdoor.jpg"
        caption: "Activiteit bij de voordeur!"
        target:
          - !secret telegram_frank_id
          - !secret telegram_malissa_id
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 10001
        ringtone_vol: 30

- alias: "Stuur bericht bij aanbellen voordeur"
  id: doorbell_pressed
  trigger:
    - platform: state
      entity_id: sensor.doorbell
      from: 'not_pressed'
      to: 'pressed'
  # condition:
  #   condition: template
  #   value_template: "{{ not is_state('input_select.timeofday', 'night') }}"
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 10
        ringtone_vol: 30
    - service: camera.snapshot
      data:
        entity_id: camera.voortuin
        filename: "/tmp/last_doorbell.jpg"
    # - delay:
    #     seconds: 3
    - service: telegram_bot.send_photo
      data:
        file: "/tmp/last_doorbell.jpg"
        caption: "Deurbel - Er staat iemand voor de deur!"
        target:
          - !secret telegram_frank_id
          - !secret telegram_malissa_id
    - service: light.turn_on
      data:
        entity_id: !secret aqara_gateway_light
        brightness_pct: 100
        color_name: blue
    - delay:
        seconds: 5
      # data_template:
      #   url: "{{ states('sensor.http_base_url') }}{{ state_attr('camera.voortuin', 'entity_picture') }}"
      #   caption: "Deurbel - Er staat iemand voor de deur!"
      #   target:
      #     - !secret telegram_frank_id
      #     - !secret telegram_malissa_id
    # - service: notify.livingroom_tv
    #   data:
    #     message: "Er staat iemand voor de deur!"
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 10
        ringtone_vol: 15

- alias: "Zet deurbel lamp uit na 60 seconden"
  trigger:
    - platform: state
      entity_id: sensor.doorbell
      from: 'pressed'
      to: 'not_pressed'
      for:
        seconds: 60
  action:
    - service: light.turn_off
      entity_id: !secret aqara_gateway_light

- alias: "Stuur bericht bij voordeur bel offline"
  trigger:
    - platform: state
      entity_id: sensor.doorbell
      to: 'unknown'
      for:
        minutes: 3
  action:
    - service: notify.telegram
      data:
        title: "Storing"
        message: "De deurbel is offline."
    - service: notify.livingroom_tv
      data:
        message: "Storing: deurbel offline"
