- alias: "Stuur bericht bij beweging maar niemand is thuis"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.livingroom_pir_0
      from: 'off'
      to: 'on'
    - platform: state
      entity_id:
        binary_sensor.kitchen_pir_0
      from: 'off'
      to: 'on'
    - platform: state
      entity_id:
        binary_sensor.hallway_pir_0
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('group.all_persons', 'not_home') }}"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.woonkamer
        filename: "/tmp/last_activity_woonkamer.jpg"
    - service: telegram_bot.send_photo
      data_template:
        file: "/tmp/last_activity_woonkamer.jpg"
        caption: "ALARM: Activity at {{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].attributes.friendly_name }}"
        target:
          - !secret telegram_frank_id
          - !secret telegram_malissa_id

- alias: "Alarm bij beweging maar niemand is thuis"
  trigger:
    - platform: state
      entity_id:
        binary_sensor.livingroom_pir_0
      from: 'off'
      to: 'on'
    - platform: state
      entity_id:
        binary_sensor.kitchen_pir_0
      from: 'off'
      to: 'on'
    - platform: state
      entity_id:
        binary_sensor.hallway_pir_0
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('group.all_persons', 'not_home') }}"
      - condition: state
        entity_id: "input_boolean.alarm_downstairs"
        state: 'on'
      - condition: template
        value_template: "{{ not is_state('input_select.timeofday', 'night') }}"
      - condition: template
        value_template: "{{ not is_state('input_select.timeofday', 'evening') }}"
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: "0"
        ringtone_vol: 100
    - delay:
        seconds: 30
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: "0"
        ringtone_vol: 100
    - delay:
        seconds: 30
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: "0"
        ringtone_vol: 100

- alias: "Ganglicht bij aanbellen voordeur"
  trigger:
    - platform: state
      entity_id: sensor.doorbell
      from: 'not_pressed'
      to: 'pressed'
    - platform: event
      event_type: dahua_event_received
      event_data:
        code: CrossLineDetection
        action: Start
  condition:
    condition: template
    value_template: "{{ is_state('input_select.timeofday', 'night') }}"
  action:
    - delay:
        seconds: 10
    - service: light.turn_on
      data_template:
        entity_id: light.hallway_lights
        brightness_pct: "{{ states('input_number.hallway_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
    - service: timer.start
      data:
        entity_id: timer.hallway
        duration: 18

- alias: "Stuur bericht bij activiteit voordeur"
  trigger:
    - platform: event
      event_type: dahua_event_received
      event_data:
        code: CrossLineDetection
        action: Start
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.voortuin
        filename: "/tmp/last_activity_frontdoor.jpg"
    - service: telegram_bot.send_photo
      data:
        file: "/tmp/last_activity_frontdoor.jpg"
        caption: "Activiteit bij de voordeur!"
        target:
          - !secret telegram_frank_id
          - !secret telegram_malissa_id

- alias: "Speel geluid bij activiteit voordeur"
  trigger:
    - platform: event
      event_type: dahua_event_received
      event_data:
        code: CrossLineDetection
        action: Start
  condition:
    condition: template
    value_template: "{{ not is_state('input_select.timeofday', 'evening') and not is_state('input_select.timeofday', 'night') }}"
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 10001
        ringtone_vol: 80

- alias: "Stuur bericht bij aanbellen voordeur"
  id: doorbell_pressed
  trigger:
    - platform: state
      entity_id: sensor.doorbell
      from: 'not_pressed'
      to: 'pressed'
  # condition:
  #   condition: template
  #   value_template: "{{ not is_state('input_select.timeofday', 'night') }}"
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 10
        ringtone_vol: 30
    - service: camera.snapshot
      data:
        entity_id: camera.voortuin
        filename: "/tmp/last_doorbell.jpg"
    # - delay:
    #     seconds: 3
    - service: telegram_bot.send_photo
      data:
        file: "/tmp/last_doorbell.jpg"
        caption: "Deurbel - Er staat iemand voor de deur!"
        target:
          - !secret telegram_frank_id
          - !secret telegram_malissa_id
    - service: light.turn_on
      data:
        entity_id: !secret aqara_gateway_light
        brightness_pct: 100
        color_name: blue
    - delay:
        seconds: 5
      # data_template:
      #   url: "{{ states('sensor.http_base_url') }}{{ state_attr('camera.voortuin', 'entity_picture') }}"
      #   caption: "Deurbel - Er staat iemand voor de deur!"
      #   target:
      #     - !secret telegram_frank_id
      #     - !secret telegram_malissa_id
    # - service: notify.livingroom_tv
    #   data:
    #     message: "Er staat iemand voor de deur!"
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 10
        ringtone_vol: 15

- alias: "Zet deurbel lamp uit na 60 seconden"
  trigger:
    - platform: state
      entity_id: sensor.doorbell
      from: 'pressed'
      to: 'not_pressed'
      for:
        seconds: 60
  action:
    - service: light.turn_off
      entity_id: !secret aqara_gateway_light

- alias: "Stuur bericht bij voordeur bel offline"
  trigger:
    - platform: state
      entity_id: sensor.doorbell
      to: 'unknown'
      for:
        minutes: 3
  action:
    - service: notify.telegram
      data:
        title: "Storing"
        message: "De deurbel is offline."
    - service: notify.livingroom_tv
      data:
        message: "Storing: deurbel offline"
