- alias: "Update Last Motion"
  trigger:
    - platform: state
      entity_id:
        sensor.attichallway_pir_0,
        sensor.closetroom_pir_0,
        sensor.hallway_pir_0,
        sensor.kitchen_pir_0,
        sensor.livingroom_pir_0,
        sensor.upperhallway_pir_0,
        sensor.toilet_pir_0,
        sensor.kitchen_door_0
      to: 'on'
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.last_motion
      data_template:
        value: "{{ trigger.to_state.attributes.friendly_name }}"
