- alias: "Update Last Motion"
  trigger:
    - platform: state
      entity_id:
        binary_sensor.attichallway_pir_0,
        binary_sensor.closetroom_pir_0,
        binary_sensor.hallway_pir_0,
        binary_sensor.kitchen_pir_0,
        binary_sensor.livingroom_pir_0,
        binary_sensor.upperhallway_pir_0
      to: 'on'
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.last_motion
      data_template:
        value: "{{ trigger.to_state.attributes.friendly_name }}"
