- alias: "Licht Overloop aan bij beweging"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        switch.upperhallway_pir_0,
        switch.upperhallway_pir_1
      to: 'on'
  condition:
    condition: template
    value_template: "{{ states('sensor.lux_livingroom')|default(0) <= states('input_number.upperhallway_darkness_treshold') }}"
  action:
    service: script.turn_on
    data_template:
      entity_id: "script.upperhallway_{{ states('input_select.timeofday') }}"

- alias: "Licht Overloop uit als timer stopt"
  initial_state: on
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.upperhallway
  action:
    service: script.turn_on
    entity_id: "script.upperhallway_off"

- alias: "Licht Overloop volgt dagdeel"
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: template
    value_template: "{{ is_state('light.upperhallway', 'on') }}"
  action:
    service: script.turn_on
    data_template:
      entity_id: "script.upperhallway_{{ states('input_select.timeofday') }}"

- alias: "Licht Overloop vol aan door muurknop"
  initial_state: on
  trigger:
  - platform: state
    entity_id: switch.hallway_switch_1
    to: "on"
  action:
    service: script.turn_on
    entity_id: script.upperhallway_full
