- alias: "Licht Gang aan bij beweging als het donker is buiten"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        sensor.hallway_pir_0
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.to_state.attributes.illuminance|default(0)|int <= states('input_number.hallway_darkness_treshold')|default(0)|int }}"
      - condition: state
        entity_id: light.hallway_lights
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.hallway_lights"
        brightness_pct: "{{ states('input_number.hallway_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
    - service: timer.cancel
      entity_id: timer.hallway

- alias: "Licht Hal blijft aan bij beweging als het donker is buiten"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        sensor.hallway_pir_0
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.hallway_lights
        state: 'on'
      - condition: template
        value_template: "{{ trigger.to_state.attributes.illuminance|default(0)|int <= states('input_number.hallway_darkness_treshold')|default(0)|int+10 }}"
  action:
    - service: timer.cancel
      entity_id: timer.hallway

- alias: Licht gang uit na configurabele tijd geen beweging
  trigger:
    platform: state
    entity_id: sensor.hallway_pir_0
    to: 'off'
  action:
    service: timer.start
    data_template:
      entity_id: timer.hallway
      duration: "{{ states('input_number.hallway_timeout')|default(60)|int }}"

- alias: "Licht Gang soms een keer aan als er niemand thuis is"
  initial_state: on
  trigger:
    - platform: time_pattern
      minutes: '/6'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_select.timeofday', 'evening') }}"
      - condition: template
        value_template: "{{ is_state('group.all_devices', 'not_home') }}"
  action:
    - service: light.turn_on
      data:
        entity_id: "light.hallway_lights"
        brightness_pct: 50
    - service: timer.start
      data:
        entity_id: timer.hallway
        duration: 42

- alias: "Licht Gang uit als timer stopt"
  initial_state: on
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hallway
  action:
    service: light.turn_off
    data:
      entity_id: light.hallway_lights

- alias: "Licht Gang volgt dagdeel"
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: state
    entity_id: light.hallway_lights
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.hallway_lights"
      brightness_pct: "{{ states('input_number.hallway_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
