- alias: "Licht Woonkamer aan bij beweging in de ochtend"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        switch.hallway_pir_0
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_select.timeofday', 'morning') }}"
      - condition: template
        value_template: "{{ not is_state('light.livingroom', 'on') }}"
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.livingroom_{{ states('input_select.timeofday') }}"

- alias: "Licht Woonkamer aan bij weinig zonlicht"
  initial_state: on
  trigger:
    - platform: numeric_state
      entity_id: sensor.pws_solarradiation
      below: 30
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_select.timeofday', 'midday') or is_state('input_select.timeofday', 'evening') }}"
      - condition: template
        value_template: "{{ not is_state('light.livingroom', 'on') }}"
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.livingroom_{{ states('input_select.timeofday') }}"

- alias: "Licht Woonkamer uit bij genoeg zonlicht overdag"
  initial_state: on
  trigger:
    - platform: numeric_state
      entity_id: sensor.pws_solarradiation
      above: 50
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_select.timeofday', 'midday') }}"
      - condition: template
        value_template: "{{ is_state('light.livingroom', 'on') }}"
  action:
    service: scene.turn_on
    entity_id: "scene.livingroom_off"

- alias: "Licht Woonkamer uit zodra we in nachtmodus gaan"
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_select.timeofday
      to: "night"
  condition:
    condition: template
    value_template: "{{ is_state('light.livingroom', 'on') }}"
  action:
    service: scene.turn_on
    entity_id: "scene.livingroom_off"

- alias: "Licht Woonkamer aan bij beweging 'snachts"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        switch.hallway_pir_0,
        switch.hallway_contact_0
      to: 'on'
  condition:
    condition: template
    value_template: "{{ is_state('input_select.timeofday', 'night') }}"
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.livingroom_{{ states('input_select.timeofday') }}"

- alias: "Licht Woonkamer uit na 5 minuten 'snachts"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        switch.hallway_pir_0,
        switch.hallway_contact_0
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: template
    value_template: "{{ is_state('input_select.timeofday', 'night') }}"
  action:
    service: scene.turn_on
    entity_id: "scene.livingroom_off"

- alias: "Licht Woonkamer volgt dagdeel"
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: template
    value_template: "{{ not is_state('light.livingroom', 'off') }}"
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.livingroom_{{ states('input_select.timeofday') }}"
