- alias: "Licht achtertuin savonds en snachts"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.garden_dark
      to: 'on'
    - platform: time_pattern # check every 5 mins and re-send ON signal, remember: 433MHz is fire and forget
      minutes: '/5'
      seconds: 00
  condition:
    condition: state
    entity_id: binary_sensor.garden_dark
    state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: "switch.scullery_power_0"

- alias: "Licht achtertuin uit sochtends en smiddags"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.garden_dark
      to: 'off'
    - platform: time_pattern # check every 5 mins and re-send ON signal, remember: 433MHz is fire and forget
      minutes: '/5'
      seconds: 00
  condition:
    condition: state
    entity_id: binary_sensor.garden_dark
    state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: "switch.scullery_power_0"
