- alias: "Licht tuin aan als het donker is"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.garden_dark
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.garden_dark
    state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: "light.porch_light_1"
    - service: switch.turn_on
      data:
        entity_id: "switch.scullery_power_0"

- alias: "Licht tuin uit als het licht is"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.garden_dark
      to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.garden_dark
    state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: "light.porch_light_1"
    - service: switch.turn_off
      data:
        entity_id: "switch.scullery_power_0"
