- alias: "Licht Keuken aan bij beweging als het donker is buiten"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        sensor.kitchen_pir_0
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.kitchen_lights
        state: 'off'
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ is_state('input_select.timeofday', 'evening') }}"
          - condition: template
            value_template: "{{ is_state('input_select.timeofday', 'night') }}"
          - condition: template
            value_template: "{{ trigger.to_state.attributes.illuminance|default(0)|int <= states('input_number.kitchen_darkness_treshold')|default(0)|int }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.kitchen_lights"
        brightness_pct: "{{ states('input_number.kitchen_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
    - service: switch.turn_on
      entity_id: "switch.garage_power_0"
    - service: timer.cancel
      entity_id: timer.kitchen

- alias: "Licht Keuken blijft aan bij beweging als het donker is buiten"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        sensor.kitchen_pir_0
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.kitchen_lights
        state: 'on'
      - condition: template
        value_template: "{{ trigger.to_state.attributes.illuminance|default(0)|int <= states('input_number.kitchen_darkness_treshold')|default(0)|int+10 }}"
  action:
    - service: timer.cancel
      entity_id: timer.kitchen

- alias: Licht Keuken uit na configurabele tijd geen beweging
  trigger:
    platform: state
    entity_id: sensor.kitchen_pir_0
    to: 'off'
  action:
    service: timer.start
    data_template:
      entity_id: timer.kitchen
      duration: "{{ states('input_number.kitchen_timeout')|default(60)|int }}"

- alias: "Licht Keuken soms een keer aan als er niemand thuis is"
  initial_state: on
  trigger:
    - platform: time_pattern
      minutes: '/16'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_select.timeofday', 'evening') }}"
      - condition: template
        value_template: "{{ is_state('group.all_devices', 'not_home') }}"
  action:
    - service: light.turn_on
      data:
        entity_id: "light.kitchen_lights"
        brightness_pct: 60
    - service: timer.start
      data:
        entity_id: timer.kitchen
        duration: 42

- alias: "Licht Keuken uit als timer stopt"
  initial_state: on
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen
  action:
    - service: light.turn_off
      data:
        entity_id: light.kitchen_lights
    - service: switch.turn_off
      entity_id: "switch.garage_power_0"

- alias: "Licht Keuken volgt dagdeel"
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: state
    entity_id: light.kitchen_lights
    state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.kitchen_lights"
        brightness_pct: "{{ states('input_number.kitchen_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
    - service: switch.turn_on
      entity_id: "switch.garage_power_0"


# - alias: Turn off kitchen light when it's light
#   trigger:
#     platform: template
#     value_template: "{{ (states('sensor.kitchen_pir_0_illuminance')|default(0)|int) > (states('input_number.kitchen_darkness_treshold')|default(0)|int + 5) }}"
#   condition:
#     condition: state
#     entity_id: light.kitchen_lights
#     state: 'on'
#   action:
#     - service: light.turn_off
#       entity_id: light.kitchen_lights
#     - service: timer.cancel
#       entity_id: timer.kitchen
