- alias: "Licht Gang aan bij beweging als het donker is buiten"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        switch.hallway_pir_0,
        switch.hallway_pir_1,
        switch.hallway_door_0
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.lux_livingroom
      below: 700
  action:
    service: script.turn_on
    data_template:
      entity_id: "script.hallway_{{ states('input_select.timeofday') }}"

- alias: "Licht Gang aan als iemand van de trap af komt"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        switch.upperhallway_pir_0
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.lux_livingroom
        below: 700
      - condition: template
        value_template: '{{ (as_timestamp(now())-as_timestamp(states.switch.upperhallway_pir_1.last_updated)) < 30 }}'
  action:
    service: script.turn_on
    data_template:
      entity_id: "script.hallway_{{ states('input_select.timeofday') }}"

- alias: "Licht Gang uit als timer stopt"
  initial_state: on
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hallway
  action:
    service: script.turn_on
    entity_id: "script.hallway_off"

- alias: "Licht Gang volgt dagdeel"
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{{ is_state('light.hallway', 'on') }}"
    - condition: template
      value_template: "{{ is_state('switch.hallway_switch_0', 'off') }}"
  action:
    service: script.turn_on
    data_template:
      entity_id: "script.hallway_{{ states('input_select.timeofday') }}"

- alias: "Licht Gang fel aan door muurknop"
  initial_state: on
  trigger:
  - platform: state
    entity_id: switch.hallway_switch_0
    to: "on"
  action:
    service: script.turn_on
    data:
      entity_id: script.hallway_full
