- alias: "Licht Overloop aan bij beweging als het donker is buiten"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.upperhallway_pir_0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.upperhallway_lights
        state: 'off'
      - condition: state
        entity_id: binary_sensor.upperhallway_pir_0
        state: 'on'
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ is_state('input_select.timeofday', 'evening') }}"
          - condition: template
            value_template: "{{ is_state('input_select.timeofday', 'night') }}"
          - condition: template
            value_template: "{{ trigger.to_state.attributes.illuminance|default(0)|int <= states('input_number.upperhallway_darkness_treshold')|default(0)|int }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.upperhallway_lights"
        brightness_pct: "{{ states('input_number.upperhallway_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
    - service: light.turn_on
      data_template:
        entity_id: "light.livingroom_light_2"
        brightness_pct: "{{ states('input_number.upperhallway_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
    - service: timer.cancel
      entity_id: timer.upperhallway

- alias: "Licht Overloop blijft aan bij beweging als het donker is buiten"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.upperhallway_pir_0
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.upperhallway_lights
        state: 'on'
      - condition: template
        value_template: "{{ trigger.to_state.attributes.illuminance|default(0)|int <= states('input_number.upperhallway_darkness_treshold')|default(0)|int+10 }}"
  action:
    - service: timer.cancel
      entity_id: timer.upperhallway

- alias: Licht Overloop uit na configurabele tijd geen beweging
  trigger:
    platform: state
    entity_id: binary_sensor.upperhallway_pir_0
    to: 'off'
  action:
    service: timer.start
    data_template:
      entity_id: timer.upperhallway
      duration: "{{ states('input_number.upperhallway_timeout')|default(60)|int }}"

- alias: "Licht Overloop soms een keer aan als er niemand thuis is"
  initial_state: on
  trigger:
    - platform: time_pattern
      minutes: '/41'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_select.timeofday', 'evening') }}"
      - condition: template
        value_template: "{{ is_state('group.all_persons', 'not_home') }}"
  action:
    - service: light.turn_on
      data:
        entity_id: "light.upperhallway_lights"
        brightness_pct: 100
    - service: timer.start
      data:
        entity_id: timer.upperhallway
        duration: 120

- alias: "Licht Overloop uit als timer stopt"
  initial_state: on
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.upperhallway
  action:
    - service: light.turn_off
      data:
        entity_id: light.upperhallway_lights
    - service: light.turn_off
      data_template:
        entity_id: "light.livingroom_light_2"


- alias: "Licht Overloop volgt dagdeel"
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: state
    entity_id: light.upperhallway_lights
    state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.upperhallway_lights"
        brightness_pct: "{{ states('input_number.upperhallway_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
    - service: light.turn_on
      data_template:
        entity_id: "light.livingroom_light_2"
        brightness_pct: "{{ states('input_number.upperhallway_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
