- alias: upperhallway_on_activity
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        switch.upperhallway_pir_0,
        switch.upperhallway_pir_1
      to: 'on'
  condition:
    condition: template 
    value_template: "{{ is_state('switch.hallway_switch_1', 'off') }}"
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.upperhallway_{{ states('input_select.timeofday') }}"

- alias: upperhallway_lights_off_during_daytime_after_1_minute_idle
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        switch.upperhallway_pir_0,
        switch.upperhallway_pir_1,
        switch.hallway_switch_1
      to: 'off'
      for:
        minutes: 1
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{{ not is_state('input_select.timeofday', 'night') }}"
    - condition: template 
      value_template: "{{ is_state('switch.hallway_switch_1', 'off') }}"
  action:
    service: scene.turn_on
    entity_id: "scene.upperhallway_off"

- alias: upperhallway_lights_off_during_nighttime_after_10_seconds_idle
  initial_state: on
  trigger:
  - platform: state
    entity_id: 
      switch.upperhallway_pir_0,
      switch.upperhallway_pir_1,
      switch.hallway_switch_1
    to: 'off'
    for:
      seconds: 10
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{{ is_state('input_select.timeofday', 'night') }}"
    - condition: template 
      value_template: "{{ is_state('switch.hallway_switch_1', 'off') }}"
  action:
    service: scene.turn_on
    entity_id: "scene.upperhallway_off"

- alias: upperhallway_lights_follow_timeofday
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: template
    value_template: "{{ not is_state('light.upperhallway', 'off') }}"
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.upperhallway_{{ states('input_select.timeofday') }}"

- alias: hallway_lights_forced_by_switch
  initial_state: on
  trigger:
  - platform: state
    entity_id: switch.hallway_switch_1
    to: "on"
  action:
    service: scene.turn_on
    entity_id: scene.upperhallway_full
