- alias: upperhallway_on_activity_when_dark
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        switch.upperhallway_pir_0,
        switch.upperhallway_pir_1,
        switch.upperhallway_contact_0
      to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.pws_solarradiation
    below: 50
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.upperhallway_{{ states('input_select.timeofday') }}"

- alias: upperhallway_lights_off_during_daytime_after_1_minute_idle
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        switch.upperhallway_pir_0,
        switch.upperhallway_pir_1,
        switch.upperhallway_contact_0
      to: 'off'
      for:
        minutes: 1
  condition:
    condition: template
    value_template: "{{ not is_state('input_select.timeofday', 'night') }}"
  action:
    service: scene.turn_on
    entity_id: "scene.upperhallway_off"

- alias: upperhallway_lights_off_during_nighttime_after_10_seconds_idle
  initial_state: on
  trigger:
  - platform: state
    entity_id: 
      switch.upperhallway_pir_0,
      switch.upperhallway_pir_1,
      switch.upperhallway_contact_0
    to: 'off'
    for:
      seconds: 10
  condition:
    condition: template
    value_template: "{{ is_state('input_select.timeofday', 'night') }}"
  action:
    service: scene.turn_on
    entity_id: "scene.upperhallway_off"

- alias: upperhallway_lights_follow_timeofday
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: template
    value_template: "{{ not is_state('light.upperhallway', 'off') }}"
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.upperhallway_{{ states('input_select.timeofday') }}"
