- alias: lights_hallway_on_activity_when_dark
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        switch.hallway_pir_0,
        switch.hallway_pir_1,
        switch.hallway_contact_0
      to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.pws_solarradiation
    below: 50
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.hallway_{{ states('input_select.timeofday') }}"

- alias: lights_hallway_on_when_coming_downstairs
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        switch.upperhallway_pir_0
      to: 'on'
  condition:
    condition: template
    value_template: '{{ (as_timestamp(now())-as_timestamp(states.switch.upperhallway_pir_1.last_updated)) < 30 }}'
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.hallway_{{ states('input_select.timeofday') }}"

- alias: hallway_lights_off_during_daytime_after_1_minute_idle
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        switch.hallway_pir_0,
        switch.hallway_pir_1,
        switch.hallway_contact_0
      to: 'off'
      for:
        minutes: 1
  condition:
    condition: template
    value_template: "{{ not is_state('input_select.timeofday', 'night') }}"
  action:
    service: scene.turn_on
    entity_id: "scene.hallway_off"

- alias: hallway_lights_off_during_nighttime_after_10_seconds_idle
  initial_state: on
  trigger:
  - platform: state
    entity_id: 
      switch.hallway_pir_0,
      switch.hallway_pir_1,
      switch.hallway_contact_0
    to: 'off'
    for:
      seconds: 10
  condition:
    condition: template
    value_template: "{{ is_state('input_select.timeofday', 'night') }}"
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.hallway_off"

- alias: hallway_lights_follow_timeofday
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: template
    value_template: "{{ not is_state('light.hallway', 'off') }}"
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.hallway_{{ states('input_select.timeofday') }}"
