- alias: "Licht Kastenkamer aan bij beweging als het donker is buiten"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        sensor.closetroom_pir_0
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.closetroom_lights
        state: 'off'
      - condition: template
        value_template: "{{ trigger.to_state.attributes.illuminance|default(0)|int <= states('input_number.closetroom_darkness_treshold')|default(0)|int }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.closetroom_lights"
        brightness_pct: "{{ states('input_number.closetroom_brightness_' + states('input_select.timeofday'))|default(100)|int }}"
    - service: timer.cancel
      entity_id: timer.closetroom

- alias: "Licht Kastenkamer soms een keer aan als er niemand thuis is"
  initial_state: on
  trigger:
    - platform: time_pattern
      minutes: '/53'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_select.timeofday', 'evening') }}"
      - condition: template
        value_template: "{{ is_state('group.all_devices', 'not_home') }}"
  action:
    - service: light.turn_on
      data:
        entity_id: "light.closetroom_lights"
        brightness_pct: 10
    - service: timer.start
      data:
        entity_id: timer.closetroom
        duration: 300

- alias: "Licht Kastenkamer blijft aan bij beweging als het donker is buiten"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        sensor.closetroom_pir_0
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.closetroom_lights
        state: 'on'
      - condition: template
        value_template: "{{ trigger.to_state.attributes.illuminance|default(0)|int <= states('input_number.closetroom_darkness_treshold')|default(0)|int+10 }}"
  action:
    - service: timer.cancel
      entity_id: timer.closetroom

- alias: Licht Kastenkamer uit na configurabele tijd geen beweging
  trigger:
    platform: state
    entity_id: sensor.closetroom_pir_0
    from: 'on'
    to: 'off'
  action:
    service: timer.start
    data_template:
      entity_id: timer.closetroom
      duration: "{{ states('input_number.closetroom_timeout')|default(60)|int }}"

# - alias: "Licht Kastenkamer soms een keer aan als er niemand thuis is"
#   initial_state: on
#   trigger:
#     - platform: time
#       minutes: '/9'
#       seconds: 00
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: "{{ is_state('input_select.timeofday', 'evening') }}"
#       - condition: template
#         value_template: "{{ is_state('group.all_devices', 'not_home') }}"
#   action:
#     - service: light.turn_on
#       entity_id: "light.closetroom_lights"
#       brightness_pct: 100
#     - service: timer.start
#       entity_id: timer.closetroom
#       duration: 42

- alias: "Licht Kastenkamer uit als timer stopt"
  initial_state: on
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.closetroom
  action:
    - service: light.turn_off
      data:
        entity_id: light.closetroom_lights

- alias: "Licht Kastenkamer volgt dagdeel"
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.timeofday
  condition:
    condition: state
    entity_id: light.closetroom_lights
    state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.closetroom_lights"
        brightness_pct: "{{ states('input_number.closetroom_brightness_' + states('input_select.timeofday'))|default(100)|int }}"

- alias: Turn off closetroom light when it's light
  trigger:
    platform: template
    value_template: "{{ (states('sensor.closetroom_pir_0_illuminance')|default(0)|int) > (states('input_number.closetroom_darkness_treshold')|default(0)|int + 10) }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.closetroom_lights
        state: 'on'
      - condition: template
        value_template: "{{ (trigger.to_state.attributes.illuminance|default(0)|int) > (states('input_number.closetroom_darkness_treshold')|default(0)|int + 5) }}"
      - condition: template
        value_template: "{{ not is_state('input_select.timeofday', 'evening') }}"
      - condition: template
        value_template: "{{ not is_state('input_select.timeofday', 'night') }}"
  action:
    - service: light.turn_off
      entity_id: light.closetroom_lights
    - service: timer.cancel
      entity_id: timer.closetroom
