- alias: "Licht Overloop aan bij beweging"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.upperhallway_pir_0
      to: 'on'
  # condition:
  #   condition: and
  #   conditions:
  #     - condition: template
  #       value_template: "{{ states('sensor.upperhallway_recent_motions') < states('input_number.upperhallway_recent_motions_treshold') }}"
  #     - condition: state
  #       entity_id: 'binary_sensor.upperhallway_dark'
  #       state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.upperhallway_light_0"
    - service: light.turn_on
      data_template:
        entity_id: "light.livingroom_light_2"

- alias: Turn off upperhallway light 1 minute after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.upperhallway_pir_0
    to: 'off'
    for:
      minutes: 1
  action:
    - service: light.turn_off
      data_template:
        entity_id: "light.upperhallway_light_0"
    - service: light.turn_off
      data_template:
        entity_id: "light.livingroom_light_2"

- alias: "Licht Zolder aan bij beweging"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.attichallway_pir_0
      to: 'on'
  # condition:
  #   condition: and
  #   conditions:
  #     - condition: template
  #       value_template: "{{ states('sensor.upperhallway_recent_motions') < states('input_number.upperhallway_recent_motions_treshold') }}"
  #     - condition: state
  #       entity_id: 'binary_sensor.upperhallway_dark'
  #       state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.attichallway_light_0"


- alias: Turn off attichallway light 1 minute after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.attichallway_pir_0
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.attichallway_light_0

- alias: "Licht Kastenkamer aan bij beweging"
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        binary_sensor.closetroom_pir_0
      to: 'on'
  # condition:
  #   condition: and
  #   conditions:
  #     - condition: template
  #       value_template: "{{ states('sensor.upperhallway_recent_motions') < states('input_number.upperhallway_recent_motions_treshold') }}"
  #     - condition: state
  #       entity_id: 'binary_sensor.upperhallway_dark'
  #       state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.closetroom_lights"

- alias: Turn off closetroom lights 3 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.closetroom_pir_0
    to: 'off'
    for:
      minutes: 3
  action:
    service: light.turn_off
    entity_id: light.closetroom_lights

# - alias: "Licht vol aan als er veel beweging is"
#   initial_state: on
#   trigger:
#   - platform: template
#     value_template: "{{ states('sensor.upperhallway_recent_motions') >= states('input_number.upperhallway_recent_motions_treshold') }}"
#   action:
#     service: switch.turn_on
#     entity_id: switch.hallway_switch_1

# - alias: "Licht Overloop uit als timer stopt"
#   initial_state: on
#   trigger:
#     - platform: event
#       event_type: timer.finished
#       event_data:
#         entity_id: timer.upperhallway
#   action:
#     service: script.turn_on
#     entity_id: "script.upperhallway_off"

# - alias: "Licht Overloop volgt dagdeel"
#   initial_state: on
#   trigger:
#   - platform: state
#     entity_id: input_select.timeofday
#   condition:
#     condition: template
#     value_template: "{{ is_state('light.upperhallway_lights', 'on') }}"
#   action:
#     service: script.turn_on
#     data_template:
#       entity_id: "script.upperhallway_{{ states('input_select.timeofday') }}"

# - alias: "Licht Overloop vol aan door muurknop"
#   initial_state: on
#   trigger:
#   - platform: state
#     entity_id: switch.hallway_switch_1
#     to: "on"
#   action:
#     service: script.turn_on
#     entity_id: script.upperhallway_full
