- alias: "woonkamer needs to be humidified"
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_humidity_too_low
      from: "off"
      to: "on"
  # condition:
  #   condition: and
  #   conditions:
  #     - condition: template
  #       value_template: "{{ is_state('input_number.bathroom_fan_last_on_humidity', '0.0') }}"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.livingroom_power_0

- alias: "woonkamer stop humidifier"
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_humidity_too_low
      to: "off"
    - platform: time_pattern # check every 5 mins and re-send OFF signal, remember: 433MHz is fire and forget
      minutes: '/5'
      seconds: 00      
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('binary_sensor.livingroom_humidity_too_low', 'off') }}"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.livingroom_power_0
