- alias: scullery leakage notification on
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.scullery_water_0
      to: 'on'
  action:
    service: notify.telegram
    data:
      title: Waterlekkage Detectie
      message: "Waterlekkage in de Bijkeuken gedetecteerd."

- alias: scullery leakage notification off
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.scullery_water_0
      from: 'on'
      to: 'off'
  action:
    service: notify.telegram
    data:
      title: Waterlekkage Detectie
      message: "Waterlekkage in de Bijkeuken opgeheven."

- alias: scullery leakage notification on
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_water_0
      to: 'on'
  action:
    service: notify.telegram
    data:
      title: Waterlekkage Detectie
      message: "Waterlekkage in de Badkamer gedetecteerd."

- alias: bathroom leakage notification off
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_water_0
      from: 'on'
      to: 'off'
  action:
    service: notify.telegram
    data:
      title: Waterlekkage Detectie
      message: "Waterlekkage in de Badkamer opgeheven."
