- alias: "Thermostaat Woonkamer omhoog als iemand naar huis gaat"
  trigger:
    - platform: state
      entity_id: binary_sensor.frank_home_direction
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.malissa_home_direction
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      # - condition: template
      #   value_template: "{{ trigger.to_state.attributes.dir_of_travel == 'towards' }}"
      - condition: template
        value_template: "{{ not states('input_select.timeofday') == 'night' }}"
      - condition: template
        value_template: "{{ is_state('sensor.woonkamer_overlay', 'True') and state_attr('climate.woonkamer', 'temperature') == 15.0 }}"
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.woonkamer
        operation_mode: "Smart schedule"
    - delay:
        seconds: 2
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hal
        operation_mode: "Smart schedule"
    # - service: script.turn_on
    #   entity_id: script.heating_home
    - service: notify.telegram
      data:
        title: Verwarming ingeschakeld
        message: "Hoppa, de verwarming staat alvast aan!"

- alias: "Thermostaat Woonkamer omlaag als we toch niet naar huis gaan"
  trigger:
    - platform: state
      entity_id: binary_sensor.frank_home_direction
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.malissa_home_direction
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('proximity.home') | float > 2 }}"
      - condition: state
        entity_id: binary_sensor.frank_home_direction
        state: 'off'
      - condition: state
        entity_id: binary_sensor.malissa_home_direction
        state: 'off'
      - condition: template
        value_template: "{{ state_attr('climate.woonkamer', 'operating_mode') == 'Smart schedule' }}"
  action:
    - service: script.turn_on
      entity_id: script.heating_away
    - service: notify.telegram
      data:
        title: Verwarming uitgeschakeld
        message: "Niemand is (meer) onderweg naar huis"

- alias: "Thermostaat Woonkamer omlaag als we van huis weg gaan"
  trigger:
  - platform: state
    entity_id: group.all_persons
    from: 'home'
    to: 'not_home'
#   - platform: numeric_state
#     entity_id: proximity.home
#     above: 5
#   - platform: state
#     entity_id: binary_sensor.frank_home_direction
#     from: 'on'
#     to: 'off'
#   - platform: state
#     entity_id: binary_sensor.malissa_home_direction
#     from: 'on'
#     to: 'off'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('proximity.home') | int >= 5 }}"
    #   - condition: state
    #     entity_id: binary_sensor.frank_home_direction
    #     state: 'off'
    #   - condition: state
    #     entity_id: binary_sensor.malissa_home_direction
    #     state: 'off'
      - condition: template
        value_template: "{{ is_state('sensor.woonkamer_overlay', 'False') or state_attr('climate.woonkamer', 'temperature') > 15.0 }}"
  action:
    - service: script.turn_on
      entity_id: script.heating_away
    - service: notify.telegram
      data:
        title: Verwarming uitgeschakeld
        message: "Iedereen heeft het huis verlaten."

- alias: "Thermostaat Woonkamer omhoog als we thuis komen en hij staat nog niet aan"
  trigger:
  - platform: state
    entity_id: group.all_persons
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      # - condition: template
      #   value_template: "{{ not states('input_select.timeofday') == 'night' }}"
      - condition: template
        value_template: "{{ is_state('sensor.woonkamer_overlay', 'True') and state_attr('climate.woonkamer', 'temperature') == 15.0 }}"
  action:
    - service: climate.set_operation_mode
      entity_id: climate.woonkamer
      data:
        operation_mode: "Smart schedule"
    - delay:
        seconds: 2
    - service: climate.set_operation_mode
      entity_id: climate.hal
      data:
        operation_mode: "Smart schedule"
    - service: notify.telegram
      data_template:
        title: Verwarming Woonkamer ingeschakeld
        message: "Hoppa, de verwarming staat aan!"

- alias: "Thermostaat Rest omhoog als we thuis komen en ze staan nog niet aan"
  trigger:
  - platform: state
    entity_id: group.all_persons
    from: 'not_home'
    to: 'home'
    for:
      minutes: 30
  condition:
    condition: and
    conditions:
      # - condition: template
      #   value_template: "{{ not states('input_select.timeofday') == 'night' }}"
      - condition: template
        value_template: "{{ not state_attr('climate.logeerkamer', 'operation_mode') == 'Smart schedule' }}"
  action:
    - service: script.turn_on
      entity_id: script.heating_home
    - service: notify.telegram
      data_template:
        title: Verwarming ingeschakeld
        message: "Bewoners in het huis gedetecteerd"

- alias: "Thermostaat Bijkeuken omhoog als de verwarming uit gaat"
  trigger:
    - platform: state
      entity_id: binary_sensor.kettle_heating
      from: 'on'
      to: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bijkeuken
        temperature: 21
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bijkeuken
        operation_mode: "Manual"

- alias: "Thermostaat Bijkeuken omlaag als het niet meer nodig is"
  trigger:
    - platform: state
      entity_id: binary_sensor.kettle_heating
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kettle_cooled_down
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.kettle_heating
        state: 'on'
      - condition: state
        entity_id: binary_sensor.kettle_cooled_down
        state: 'on'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bijkeuken
        operation_mode: "Smart schedule"
