- alias: "Thermostaat Woonkamer omhoog als iemand naar huis gaat"
  trigger:
    - platform: state
      entity_id: binary_sensor.frank_home_direction
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.malissa_home_direction
      from: 'off'
      to: 'on'
    - platform: numeric_state
      entity_id: proximity.home
      below: 17
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ is_state('binary_sensor.frank_home_direction', 'on') }}"
          - condition: template
            value_template: "{{ is_state('binary_sensor.malissa_home_direction', 'on') }}"
      - condition: state
        entity_id: binary_sensor.thermostat_leaving_next_hour
        state: 'off'
      - condition: template
        value_template: "{{ is_state('sensor.woonkamer_overlay', 'True') }}"
      - condition: numeric_state
        entity_id: proximity.home
        below: 17
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.woonkamer
        hvac_mode: auto
    - service: notify.telegram
      data:
        title: Verwarming ingeschakeld
        message: "Hoppa, de verwarming staat alvast aan!"

- alias: "Thermostaat Woonkamer omlaag als we toch niet naar huis gaan"
  trigger:
    - platform: state
      entity_id: binary_sensor.frank_home_direction
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.malissa_home_direction
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('proximity.home') | float > 2 }}"
      - condition: state
        entity_id: binary_sensor.frank_home_direction
        state: 'off'
      - condition: state
        entity_id: binary_sensor.malissa_home_direction
        state: 'off'
      - condition: template
        value_template: "{{ state_attr('climate.woonkamer', 'operating_mode') == 'Smart schedule' }}"
  action:
    - service: script.turn_on
      entity_id: script.heating_away
    - service: notify.telegram
      data:
        title: Verwarming uitgeschakeld
        message: "Niemand is (meer) onderweg naar huis"

- alias: "Thermostaat Woonkamer omlaag als we van huis weg gaan"
  trigger:
  - platform: state
    entity_id: group.all_persons
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2 # interval of nmap device_tracker is 30s so we dont want this to trigger on startup of HA
#   - platform: numeric_state
#     entity_id: proximity.home
#     above: 5
#   - platform: state
#     entity_id: binary_sensor.frank_home_direction
#     from: 'on'
#     to: 'off'
#   - platform: state
#     entity_id: binary_sensor.malissa_home_direction
#     from: 'on'
#     to: 'off'
  condition:
    condition: and
    conditions:
      # - condition: template
      #   value_template: "{{ states('proximity.home') | int >= 5 }}"
    #   - condition: state
    #     entity_id: binary_sensor.frank_home_direction
    #     state: 'off'
    #   - condition: state
    #     entity_id: binary_sensor.malissa_home_direction
    #     state: 'off'
      - condition: template
        value_template: "{{ is_state('sensor.woonkamer_overlay', 'False') or state_attr('climate.woonkamer', 'temperature') > 15.0 }}"
  action:
    - service: script.turn_on
      entity_id: script.heating_away
    - service: notify.telegram
      data:
        title: Verwarming uitgeschakeld
        message: "Iedereen heeft het huis verlaten."

- alias: "Thermostaat Woonkamer omlaag als we bijna vertrekken"
  trigger:
  - platform: state
    entity_id: binary_sensor.thermostat_leaving_next_hour
    from: 'off'
    to: 'on'
#   condition:
#     condition: and
#     conditions:
#       # - condition: template
#       #   value_template: "{{ states('proximity.home') | int >= 5 }}"
#     #   - condition: state
#     #     entity_id: binary_sensor.frank_home_direction
#     #     state: 'off'
#     #   - condition: state
#     #     entity_id: binary_sensor.malissa_home_direction
#     #     state: 'off'
#       - condition: template
#         value_template: "{{ is_state('sensor.woonkamer_overlay', 'False') or state_attr('climate.woonkamer', 'temperature') > 15.0 }}"
  action:
    - service: script.turn_on
      entity_id: script.heating_away
    - service: notify.telegram
      data_template:
        title: "Verwarming uitgeschakeld"
        message: "Vertrektijd \"{{ state_attr('calendar.malissa_frank', 'message') }}\" is binnen een uur ({{ (as_timestamp(states('sensor.calendar_malissa_frank_start_time')) - (state_attr('sensor.waze_calendar_to_next_appointment', 'duration') * 60))|timestamp_custom('%H:%M', true) }})."

- alias: "Thermostaat Woonkamer omhoog als we thuis komen en hij staat nog niet aan"
  trigger:
  - platform: state
    entity_id: group.all_persons
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      # - condition: template
      #   value_template: "{{ not states('input_select.timeofday') == 'night' }}"
      - condition: template
        value_template: "{{ is_state('sensor.woonkamer_overlay', 'True') }}"
      - condition: state
        entity_id: binary_sensor.thermostat_leaving_next_hour
        state: 'off'
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.woonkamer
      data:
        hvac_mode: auto
    - service: notify.telegram
      data_template:
        title: Verwarming Woonkamer ingeschakeld
        message: "Hoppa, de verwarming staat aan!"

- alias: "Thermostaat Rest omhoog als we thuis komen en ze staan nog niet aan"
  trigger:
  - platform: state
    entity_id: group.all_persons
    from: 'not_home'
    to: 'home'
    for:
      minutes: 60
  condition:
    condition: and
    conditions:
      # - condition: template
      #   value_template: "{{ not states('input_select.timeofday') == 'night' }}"
      - condition: state
        entity_id: binary_sensor.thermostat_leaving_next_hour
        state: 'off'
      - condition: template
        value_template: "{{ not state_attr('climate.logeerkamer', 'hvac_mode') == 'auto' }}"
  action:
    - service: script.turn_on
      entity_id: script.heating_home
    - service: notify.telegram
      data_template:
        title: Verwarming ingeschakeld
        message: "Bewoners in het huis gedetecteerd"

- alias: "Thermostaat Bijkeuken omhoog als de verwarming uit gaat"
  trigger:
    - platform: state
      entity_id: binary_sensor.kettle_heating
      from: 'on'
      to: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bijkeuken
        temperature: 25
        hvac_mode: heat

- alias: "Thermostaat Bijkeuken omlaag als het niet meer nodig is"
  trigger:
    - platform: state
      entity_id: binary_sensor.kettle_heating
      from: 'off'
      to: 'on'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.bijkeuken
        hvac_mode: "auto"
