- alias: Stuur bericht als er afval aan de straat moet de volgende dag
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.time') + ':00') == states('input_datetime.trash_announcement_time') }}"
  condition:
    condition: template
    value_template: "{{ not is_state('sensor.trash_tomorrow', '') }}"
  action:
    # - service: notify.telegram
    #   data_template:
    #     title: "Afval morgen: {{ states.sensor.trash_tomorrow.state }}"
    #     message: "Morgen moet het volgende afval aan de straat: {{ states.sensor.trash_tomorrow.state }}"
    - service: notify.mobile_app_malissa_s9
      data_template:
        title: "Afval morgen: {{ states.sensor.trash_tomorrow.state }}"
        message: "Morgen moet het volgende afval aan de straat: {{ states.sensor.trash_tomorrow.state }}"
    - service: notify.mobile_app_frank_s8p
      data_template:
        title: "Afval morgen: {{ states.sensor.trash_tomorrow.state }}"
        message: "Morgen moet het volgende afval aan de straat: {{ states.sensor.trash_tomorrow.state }}"
