- alias: "Notify Malissa traveltime to work"
  trigger:
    - platform: time
      at: '06:15'
    - platform: time
      at: '06:30'
    - platform: time
      at: '06:45'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.malissa_g5
        state: 'home'
      - condition: time
        weekday:
          - mon
          - wed
  action:
    service: notify.web_malissa_g5
    data_template:
      title: "Reistijd naar werk"
      message: "{{ states('sensor.waze_malissa_home_to_work') }} {{ states.sensor.waze_malissa_home_to_work.attributes.unit_of_measurement }} via {{ states.sensor.waze_malissa_home_to_work.attributes.route }}"
      data:
        tag: "waze-travel-home-to-work-notification"

- alias: "Notify Malissa traveltime to home"
  trigger:
    - platform: time
      at: '17:15'
    - platform: time
      at: '17:30'
    - platform: time
      at: '17:45'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.malissa_g5
        state: 'not_home'
      - condition: time
        weekday:
          - mon
          - wed
  action:
    service: notify.web_malissa_g5
    data_template:
      title: "Reistijd naar huis"
      message: "{{ states('sensor.waze_malissa_work_to_home') }} {{ states.sensor.waze_malissa_work_to_home.attributes.unit_of_measurement }} via {{ states.sensor.waze_malissa_work_to_home.attributes.route }}"
      data:
        tag: "waze-travel-work-to-home-notification"

- alias: "Notify Frank traveltime to work"
  trigger:
    - platform: time
      at: '06:30'
    - platform: time
      at: '06:45'
    - platform: time
      at: '07:00'
    - platform: time
      at: '07:15'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.frank_s8p
        state: 'home'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    service: notify.web_frank_s8p
    data_template:
      title: "Reistijd naar werk"
      message: "{{ states('sensor.waze_frank_home_to_work') }} {{ states.sensor.waze_frank_home_to_work.attributes.unit_of_measurement }} via {{ states.sensor.waze_frank_home_to_work.attributes.route }}"
      data:
        tag: "waze-travel-home-to-work-notification"

- alias: "Notify Frank traveltime to home"
  trigger:
    - platform: time
      at: '16:25'
    - platform: time
      at: '16:40'
    - platform: time
      at: '16:55'
    - platform: time
      at: '17:10'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.frank_s8p
        state: 'not_home'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    service: notify.web_frank_s8p
    data_template:
      title: "Reistijd naar huis"
      message: "{{ states('sensor.waze_frank_work_to_home') }} {{ states.sensor.waze_frank_work_to_home.attributes.unit_of_measurement }} via {{ states.sensor.waze_frank_work_to_home.attributes.route }}"
      data:
        tag: "waze-travel-work-to-home-notification"

- alias: "Notify Frank traveltime to Malissa"
  trigger:
    - platform: time
      at: '16:25'
    - platform: time
      at: '16:40'
    - platform: time
      at: '16:55'
    - platform: time
      at: '17:10'
    - platform: time
      at: '17:25'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.frank_s8p
        state: 'not_home'
      - condition: time
        weekday:
          - tue
          - thu
  action:
    service: notify.web_frank_s8p
    data_template:
      title: "Reistijd naar Malissa Utrecht"
      message: "{{ states('sensor.waze_frank_work_to_malissa_work') }} {{ states.sensor.waze_frank_work_to_malissa_work.attributes.unit_of_measurement }} via {{ states.sensor.waze_frank_work_to_malissa_work.attributes.route }}"
      data:
        tag: "waze-travel-work-to-malissa-work-notification"

- alias: "Notify Malissa when Frank is at Malissa Work 0"
  trigger:
    - platform: numeric_state
      entity_id: proximity.malissa_work_0_frank
      below: 0.5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.frank_s8p
        state: 'not_home'
      - condition: template
        value_template: "{{ states.proximity.malissa_work_0_frank.attributes.dir_of_travel != 'away_from' }}"
      - condition: time
        after: '16:00:00'
        before: '19:00:00'
        weekday:
          - tue
          - thu
  action:
    service: notify.web_malissa_g5
    data_template:
      title: "Aankomstmelding Frank"
      message: "Frank staat voor de deur!"
      data:
        tag: "waze-travel-frank-work-to-malissa-work-notification"

- alias: "Notify Malissa when Frank is heading to Malissa Work"
  trigger:
    - platform: state
      entity_id: proximity.malissa_work_0_frank
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.to_state.attributes.dir_of_travel == 'towards' }}"
      - condition: time
        after: '16:00:00'
        before: '19:00:00'
        weekday:
          - tue
          - thu
  action:
    service: notify.web_malissa_g5
    data_template:
      title: "Vertrekmelding Frank"
      message: "Frank is onderweg naar Utrecht. ETA: {{ states('sensor.waze_frank_work_to_malissa_work') }} {{ states.sensor.waze_frank_work_to_malissa_work.attributes.unit_of_measurement }}"
      data:
        tag: "waze-travel-frank-work-home-notification"

# - alias: "Notify Malissa when Frank is heading home"
#   trigger:
#     - platform: state
#       entity_id: proximity.frank_home
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: "{{ trigger.to_state.attributes.dir_of_travel == 'towards' }}"
#       - condition: time
#         after: '16:30:00'
#         before: '19:00:00'
#         weekday:
#           - mon
#           - wed
#           - fri
#   action:
#     service: notify.web_malissa_g5
#     data_template:
#       title: "Vertrekmelding Frank"
#       message: "Frank is onderweg naar huis. ETA: {{ states('sensor.waze_frank_work_to_home') }} {{ states.sensor.waze_frank_work_to_home.attributes.unit_of_measurement }}"
#       data:
#         tag: "waze-travel-frank-work-home-notification"
