- alias: "Notify on battery low for zigbee sensors"
  trigger:
    - platform: numeric_state
      entity_id:
        sensor.attichallway_switch_0_battery,
        sensor.closetroom_pir_0_battery,
        sensor.hallway_pir_0_battery,
        sensor.kitchen_pir_0_battery,
        sensor.livingroom_pir_0_battery,
        sensor.livingroom_smoke_0_battery,
        sensor.upperhallway_pir_0_battery,
        sensor.scullery_smoke_0_battery
      below: 25
  action:
    - service: notify.web
      data_template:
        title: "Low Battery: {{ trigger.entity_id.split('.')[1][:-8] }}"
        message: "The battery of {{ trigger.entity_id.split('.')[1][:-8] }} is now {{ trigger.to_state.state }}%."
