- alias: "Notify on low linkquality for zigbee sensors"
  initial_state: off
  trigger:
    - platform: numeric_state
      entity_id:
        sensor.kitchen_pir_0_linkquality,
        sensor.hallway_pir_0_linkquality,
        sensor.attichallway_pir_0_linkquality,
        sensor.upperhallway_pir_0_linkquality,
        sensor.attichallway_smoke_0_linkquality,
        sensor.livingroom_smoke_0_linkquality,
        sensor.garage_power_0_linkquality,
        sensor.bathroom_temp_0_linkquality,
        sensor.bathroom_temp_0_linkquality,
        sensor.scullery_water_0_linkquality,
        sensor.bathroom_water_0_linkquality,
        sensor.closetroom_pir_0_linkquality
      below: 5
  action:
    - service: notify.web_frank_s8p
      data_template:
        title: "Low Link Quality: {{ trigger.entity_id.split('.')[1][:-12] }}"
        message: "The link quality of {{ trigger.entity_id.split('.')[1][:-12] }} is now {{ trigger.to_state.state }}."
