- alias: "Notify on low linkquality for zigbee sensors"
  initial_state: off
  trigger:
    - platform: numeric_state
      entity_id:
        sensor.kitchen_pir_0_linkquality,
        sensor.hallway_pir_0_linkquality,
        sensor.attichallway_pir_0_linkquality,
        sensor.upperhallway_pir_0_linkquality,
        sensor.scullery_smoke_0_linkquality,
        sensor.livingroom_smoke_0_linkquality,
        sensor.garage_power_0_linkquality,
        sensor.bathroom_temp_0_linkquality,
        sensor.livingroom_temp_0_linkquality,
        sensor.scullery_water_0_linkquality,
        sensor.bathroom_water_0_linkquality,
        sensor.closetroom_pir_0_linkquality
      below: 5
  action:
    - service: notify.telegram_frank
      data_template:
        title: "Low Link Quality: {{ trigger.entity_id.split('.')[1][:-12] }}"
        message: "The link quality of {{ trigger.entity_id.split('.')[1][:-12] }} is now {{ trigger.to_state.state }}."

- alias: "Notify on last_updated timeout"
  trigger:
    - platform: numeric_state
      entity_id: binary_sensor.livingroom_smoke_0
      value_template: "{{ as_timestamp(now()) - as_timestamp(state.last_seen) }}"
      above: 3540 # 59 mins
    - platform: numeric_state
      entity_id: binary_sensor.garage_smoke_0
      value_template: "{{ as_timestamp(now()) - as_timestamp(state.last_seen) }}"
      above: 3540 # 59 mins
    - platform: numeric_state
      entity_id: binary_sensor.attic_gasco_0_co
      value_template: "{{ as_timestamp(now()) - as_timestamp(state.last_seen) }}"
      above: 3540 # 59 mins
    - platform: numeric_state
      entity_id: binary_sensor.scullery_smoke_0
      value_template: "{{ as_timestamp(now()) - as_timestamp(state.last_seen) }}"
      above: 3540 # 59 mins
    - platform: numeric_state
      entity_id: sensor.bathroom_temp_0
      value_template: "{{ as_timestamp(now()) - as_timestamp(state.last_seen) }}"
      above: 3540 # 59 mins
  action:
    - service: notify.telegram_frank
      data_template:
        title: "[ZB2MQTT] Heartbeat Timeout"
        message: "Last heartbeat of {{ trigger.entity_id.split('.')[1] }} was at {{ as_timestamp(trigger.to_state.state.last_seen)|timestamp_custom('%a %H:%M', True) }}."


- alias: "Notify on gas_co test"
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('sensor.attic_gasco_0_co', 'test', True) }}"
    - platform: template
      value_template: "{{ is_state_attr('sensor.attic_gasco_0_smoke', 'test', True) }}"
  action:
    - service: notify.telegram
      data_template:
        title: "Zigbee Sensor Test Succeeded"
        message: "Sensor {{ trigger.entity_id.split('.')[1] }} sent a test signal."
