- alias: zigbee2mqtt permit_join notification
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.zigbee2mqtt_permit_join
  action:
    service: notify.telegram_frank
    data_template:
      title: Zigbee2MQTT
      message: "Pairing mode {{ trigger.to_state.state }}."

- alias: zigbee2mqtt permit_join timeout
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.zigbee2mqtt_permit_join
      to: 'on'
      for:
        minutes: 5
  action:
    service: switch.turn_off
    data_template:
      entity_id: "{{ trigger.entity_id }}"

- alias: zigbee2mqtt log
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/bridge/log
    encoding: "utf-8"
  action:
    service: telegram_bot.send_message
    data_template:
      target:
        - !secret telegram_frank_id
      parse_mode: html
      title: "[ZB2M] {{ trigger.payload_json['type'] }}"
      message: "{{ trigger.payload_json['message'] }}, meta: {{ trigger.payload_json['meta'] | default('N/A') }}"
