- platform: here_travel_time
  name: here_frank_to_home
  app_id: !secret here_travel_time_app_id
  app_code: !secret here_travel_time_app_code
  origin_entity_id: device_tracker.frank_gps
  destination_entity_id: zone.home
  scan_interval: 120

- platform: here_travel_time
  name: here_malissa_to_home
  app_id: !secret here_travel_time_app_id
  app_code: !secret here_travel_time_app_code
  origin_entity_id: device_tracker.malissa_gps
  destination_entity_id: zone.home
  scan_interval: 120
