# - platform: history_stats
#   name: upperhallway_recent_motions
#   entity_id: group.upperhallway_pirs
#   state: 'on'
#   type: count
#   start: "{{ as_timestamp(now())|int - states('input_number.upperhallway_recent_motions_seconds')|int }}"
#   end: '{{ now() }}'

- platform: template
  sensors:
    last_motion:
      value_template: "{{ states('input_text.last_motion') }}"
