- platform: mqtt
  name: "Lux Livingroom"
  state_topic: "zstr/livingroom/lux1"
  unit_of_measurement: "lx"
- platform: mqtt
  name: "Temperature Livingroom"
  state_topic: "zstr/livingroom/temp1"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Luchtvochtigheid Livingroom"
  unit_of_measurement: "%"
  state_topic: "zstr/livingroom/humid1"
