- platform: mqtt
  name: livingroom_smoke_0_linkquality
  state_topic: "zigbee2mqtt/livingroom_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/livingroom_smoke_0"

- platform: mqtt
  name: livingroom_smoke_0_battery
  state_topic: "zigbee2mqtt/livingroom_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/livingroom_smoke_0"
  expire_after: 3600

- platform: mqtt
  name: attic_smoke_0_linkquality
  state_topic: "zigbee2mqtt/attic_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/attic_smoke_0"

- platform: mqtt
  name: attic_smoke_0_battery
  state_topic: "zigbee2mqtt/attic_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/attic_smoke_0"
  expire_after: 3600

- platform: mqtt
  name: garage_smoke_0_linkquality
  state_topic: "zigbee2mqtt/garage_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/garage_smoke_0"

- platform: mqtt
  name: garage_smoke_0_battery
  state_topic: "zigbee2mqtt/garage_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/garage_smoke_0"
  expire_after: 3600

- platform: mqtt
  name: scullery_smoke_0_linkquality
  state_topic: "zigbee2mqtt/scullery_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/scullery_smoke_0"

- platform: mqtt
  name: scullery_smoke_0_battery
  state_topic: "zigbee2mqtt/scullery_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/scullery_smoke_0"

- platform: mqtt
  name: attic_gasco_0_linkquality
  state_topic: "zigbee2mqtt/attic_gasco_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/attic_gasco_0"

# - platform: mqtt
#   name: attic_gasco_0_battery
#   state_topic: "zigbee2mqtt/attic_gasco_0"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   unit_of_measurement: "%"
#   qos: 1
#   value_template: "{{ value_json.battery|int }}"
#   json_attributes_topic: "zigbee2mqtt/attic_gasco_0"

- platform: mqtt
  name: upperhallway_smoke_0_linkquality
  state_topic: "zigbee2mqtt/upperhallway_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/upperhallway_smoke_0"

- platform: mqtt
  name: upperhallway_smoke_0_battery
  state_topic: "zigbee2mqtt/upperhallway_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/upperhallway_smoke_0"

- platform: mqtt
  name: attic_smoke_0_linkquality
  state_topic: "zigbee2mqtt/attic_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/attic_smoke_0"

- platform: mqtt
  name: attic_smoke_0_battery
  state_topic: "zigbee2mqtt/attic_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/attic_smoke_0"
