- platform: mqtt
  name: main_power_usage
  state_topic: "sensor/power_meter/watt"
  unit_of_measurement: "W"

- platform: mqtt
  name: main_power_direction
  state_topic: "sensor/power_meter/direction"

# - platform: mqtt
  # schema: json
#   name: "Lux Livingroom"
#   state_topic: "zstr/livingroom/lux1"
#   unit_of_measurement: "lx"
# - platform: mqtt
  # schema: json
#   name: "Temperature Livingroom"
#   state_topic: "zstr/livingroom/temp1"
#   unit_of_measurement: "°C"
# - platform: mqtt
  # schema: json
#   name: "Luchtvochtigheid Livingroom"
#   unit_of_measurement: "%"
#   state_topic: "zstr/livingroom/humid1"

- platform: mqtt
  name: zigbee2mqtt_status
  state_topic: "zigbee2mqtt/bridge/state"

- platform: mqtt
  name: garage_power_0
  state_topic: "zigbee2mqtt/garage_power_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "Watt"
  qos: 1
  icon: "mdi:flash"
  value_template: "{{ value_json.power|int }}"
  json_attributes_topic: "zigbee2mqtt/garage_power_0"

- platform: mqtt
  name: garage_power_0_linkquality
  state_topic: "zigbee2mqtt/garage_power_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/garage_power_0"

- platform: mqtt
  name: hallway_pir_0_battery
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/hallway_pir_0"

- platform: mqtt
  name: hallway_pir_0_linkquality
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/hallway_pir_0"

- platform: mqtt
  name: upperhallway_pir_0_illuminance
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes_topic: "zigbee2mqtt/upperhallway_pir_0"

- platform: mqtt
  name: upperhallway_pir_0_linkquality
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/upperhallway_pir_0"

- platform: mqtt
  name: upperhallway_pir_0_battery
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/upperhallway_pir_0"

- platform: mqtt
  name: closetroom_pir_0_illuminance
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes_topic: "zigbee2mqtt/closetroom_pir_0"

- platform: mqtt
  name: closetroom_pir_0_linkquality
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/closetroom_pir_0"

- platform: mqtt
  name: closetroom_pir_0_battery
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/closetroom_pir_0"

- platform: mqtt
  name: attichallway_pir_0_illuminance
  state_topic: "zigbee2mqtt/attichallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes_topic: "zigbee2mqtt/attichallway_pir_0"

- platform: mqtt
  name: attichallway_pir_0_linkquality
  state_topic: "zigbee2mqtt/attichallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/attichallway_pir_0"

- platform: mqtt
  name: attichallway_pir_0_battery
  state_topic: "zigbee2mqtt/attichallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/attichallway_pir_0"

- platform: mqtt
  name: livingroom_pir_0_illuminance
  state_topic: "zigbee2mqtt/livingroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes_topic: "zigbee2mqtt/livingroom_pir_0"

- platform: mqtt
  name: livingroom_pir_0_linkquality
  state_topic: "zigbee2mqtt/livingroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/livingroom_pir_0"

- platform: mqtt
  name: livingroom_pir_0_battery
  state_topic: "zigbee2mqtt/livingroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/livingroom_pir_0"

- platform: mqtt
  name: kitchen_pir_0_illuminance
  state_topic: "zigbee2mqtt/kitchen_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes_topic: "zigbee2mqtt/kitchen_pir_0"

- platform: mqtt
  name: hallway_pir_0_illuminance
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes_topic: "zigbee2mqtt/hallway_pir_0"

- platform: mqtt
  name: kitchen_pir_0_linkquality
  state_topic: "zigbee2mqtt/kitchen_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/kitchen_pir_0"

- platform: mqtt
  name: kitchen_pir_0_battery
  state_topic: "zigbee2mqtt/kitchen_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/kitchen_pir_0"

- platform: mqtt
  name: kitchen_door_0_linkquality
  state_topic: "zigbee2mqtt/kitchen_door_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/kitchen_door_0"

- platform: mqtt
  name: kitchen_door_0_battery
  state_topic: "zigbee2mqtt/kitchen_door_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/kitchen_door_0"

- platform: mqtt
  name: bathroom_temp_0_temperature
  state_topic: "zigbee2mqtt/bathroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:temperature-celsius"
  value_template: "{{ value_json.temperature }}"
  json_attributes_topic: "zigbee2mqtt/bathroom_temp_0"

- platform: mqtt
  name: bathroom_temp_0_humidity
  state_topic: "zigbee2mqtt/bathroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes_topic: "zigbee2mqtt/bathroom_temp_0"

- platform: mqtt
  name: bathroom_temp_0_battery
  state_topic: "zigbee2mqtt/bathroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/bathroom_temp_0"

- platform: mqtt
  name: bathroom_temp_0_linkquality
  state_topic: "zigbee2mqtt/bathroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/bathroom_temp_0"

- platform: mqtt
  name: livingroom_temp_0_temperature
  state_topic: "zigbee2mqtt/livingroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:temperature-celsius"
  value_template: "{{ value_json.temperature }}"
  json_attributes_topic: "zigbee2mqtt/livingroom_temp_0"

- platform: mqtt
  name: livingroom_temp_0_humidity
  state_topic: "zigbee2mqtt/livingroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes_topic: "zigbee2mqtt/livingroom_temp_0"

- platform: mqtt
  name: livingroom_temp_0_battery
  state_topic: "zigbee2mqtt/livingroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/livingroom_temp_0"

- platform: mqtt
  name: livingroom_temp_0_linkquality
  state_topic: "zigbee2mqtt/livingroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/livingroom_temp_0"

- platform: mqtt
  name: bathroom_water_0_battery
  state_topic: "zigbee2mqtt/bathroom_water_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/bathroom_water_0"

- platform: mqtt
  name: bathroom_water_0_linkquality
  state_topic: "zigbee2mqtt/bathroom_water_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/bathroom_water_0"

- platform: mqtt
  name: scullery_water_0_battery
  state_topic: "zigbee2mqtt/scullery_water_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/scullery_water_0"

- platform: mqtt
  name: scullery_water_0_linkquality
  state_topic: "zigbee2mqtt/scullery_water_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/scullery_water_0"

- platform: "mqtt"
  name: bed_tilt_0
  state_topic: "zigbee2mqtt/bed_tilt_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:gesture-double-tap"
  value_template: "{{ value_json.action }}"
  json_attributes_topic: "zigbee2mqtt/bed_tilt_0"
  # expire_after: 1

- platform: mqtt
  name: bed_tilt_0_battery
  state_topic: "zigbee2mqtt/bed_tilt_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/bed_tilt_0"

- platform: mqtt
  name: bed_tilt_0_linkquality
  state_topic: "zigbee2mqtt/bed_tilt_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/bed_tilt_0"

- platform: "mqtt"
  name: bed_tilt_1
  state_topic: "zigbee2mqtt/bed_tilt_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:gesture-double-tap"
  value_template: "{{ value_json.action }}"
  # expire_after: 1

- platform: mqtt
  name: bed_tilt_1_battery
  state_topic: "zigbee2mqtt/bed_tilt_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes_topic: "zigbee2mqtt/bed_tilt_1"

- platform: mqtt
  name: bed_tilt_1_linkquality
  state_topic: "zigbee2mqtt/bed_tilt_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "dBm"
  value_template: "{{ (-87+(value_json.linkquality|int)*(10--87)/255)|int }}"
  json_attributes_topic: "zigbee2mqtt/bed_tilt_1"
