# - platform: mqtt
#   name: "Lux Livingroom"
#   state_topic: "zstr/livingroom/lux1"
#   unit_of_measurement: "lx"
# - platform: mqtt
#   name: "Temperature Livingroom"
#   state_topic: "zstr/livingroom/temp1"
#   unit_of_measurement: "°C"
# - platform: mqtt
#   name: "Luchtvochtigheid Livingroom"
#   unit_of_measurement: "%"
#   state_topic: "zstr/livingroom/humid1"

- platform: mqtt
  name: zigbee2mqtt_status
  state_topic: "zigbee2mqtt/bridge/state"

- platform: mqtt
  name: garage_power_0
  state_topic: "zigbee2mqtt/garage_power_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "Watt"
  qos: 1
  icon: "mdi:flash"
  value_template: "{{ value_json.power|int }}"
  json_attributes:
    - "voltage"
    - "temperature"
    - "consumption"
    - "current"
    - "power_factor"

- platform: mqtt
  name: garage_power_0_linkquality
  state_topic: "zigbee2mqtt/garage_power_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "voltage"

- platform: mqtt
  name: livingroom_smoke_0_linkquality
  state_topic: "zigbee2mqtt/livingroom_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: livingroom_smoke_0_battery
  state_topic: "zigbee2mqtt/livingroom_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: attichallway_smoke_0_linkquality
  state_topic: "zigbee2mqtt/attichallway_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: attichallway_smoke_0_battery
  state_topic: "zigbee2mqtt/attichallway_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: hallway_pir_0_battery
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: hallway_pir_0_linkquality
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: upperhallway_pir_0_illuminance
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: upperhallway_pir_0_linkquality
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: upperhallway_pir_0_battery
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: closetroom_pir_0_illuminance
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: closetroom_pir_0_linkquality
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: closetroom_pir_0_battery
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: attichallway_pir_0_illuminance
  state_topic: "zigbee2mqtt/attichallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: attichallway_pir_0_linkquality
  state_topic: "zigbee2mqtt/attichallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: attichallway_pir_0_battery
  state_topic: "zigbee2mqtt/attichallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: livingroom_pir_0_illuminance
  state_topic: "zigbee2mqtt/livingroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: livingroom_pir_0_linkquality
  state_topic: "zigbee2mqtt/livingroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: livingroom_pir_0_battery
  state_topic: "zigbee2mqtt/livingroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: kitchen_pir_0_illuminance
  state_topic: "zigbee2mqtt/kitchen_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: kitchen_pir_0_linkquality
  state_topic: "zigbee2mqtt/kitchen_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: kitchen_pir_0_battery
  state_topic: "zigbee2mqtt/kitchen_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: freezer_temp_0_temperature
  state_topic: "zigbee2mqtt/freezer_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:temperature-celsius"
  value_template: "{{ value_json.temperature }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: freezer_temp_0_humidity
  state_topic: "zigbee2mqtt/freezer_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: freezer_temp_0_battery
  state_topic: "zigbee2mqtt/freezer_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: freezer_temp_0_linkquality
  state_topic: "zigbee2mqtt/freezer_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: bathroom_temp_0_temperature
  state_topic: "zigbee2mqtt/bathroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:temperature-celsius"
  value_template: "{{ value_json.temperature }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: bathroom_temp_0_humidity
  state_topic: "zigbee2mqtt/bathroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: bathroom_temp_0_battery
  state_topic: "zigbee2mqtt/bathroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: bathroom_temp_0_linkquality
  state_topic: "zigbee2mqtt/bathroom_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: bathroom_water_0_battery
  state_topic: "zigbee2mqtt/bathroom_water_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: bathroom_water_0_linkquality
  state_topic: "zigbee2mqtt/bathroom_water_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: scullery_water_0_battery
  state_topic: "zigbee2mqtt/scullery_water_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: scullery_water_0_linkquality
  state_topic: "zigbee2mqtt/scullery_water_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "battery"
    - "voltage"
