- platform: "mqtt"
  name: hallway_switch_0
  state_topic: "zigbee2mqtt/hallway_switch_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"
  json_attributes: 
    - "battery"
    - "voltage"
    - "action"
    - "duration"
    - "linkquality"

- platform: "mqtt"
  name: hallway_switch_0_battery
  state_topic: "zigbee2mqtt/hallway_switch_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.battery|int }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: hallway_switch_0_linkquality
  state_topic: "zigbee2mqtt/hallway_switch_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: hallway_smoke_0_linkquality
  state_topic: "zigbee2mqtt/hallway_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: hallway_smoke_0_battery
  state_topic: "zigbee2mqtt/hallway_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.battery|int }}"
  json_attributes: 
    - "battery"
    - "voltage"
  
- platform: "mqtt"
  name: hallway_pir_0_battery
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.battery|int }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: hallway_pir_0_linkquality
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.linkquality }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: hallway_pir_1_illuminance
  state_topic: "zigbee2mqtt/hallway_pir_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: hallway_pir_1_linkquality
  state_topic: "zigbee2mqtt/hallway_pir_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.linkquality }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: hallway_pir_1_battery
  state_topic: "zigbee2mqtt/hallway_pir_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.battery|int }}"
  json_attributes: 
    - "battery"
    - "voltage"
