# - platform: mqtt
#   name: hallway_switch_0
#   state_topic: "zigbee2mqtt/hallway_switch_0"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   icon: "mdi:toggle-switch"
#   value_template: "{{ value_json.click }}"
#   json_attributes:
#     - "battery"
#     - "voltage"
#     - "action"
#     - "duration"
#     - "linkquality"

# - platform: mqtt
#   name: hallway_switch_0_battery
#   state_topic: "zigbee2mqtt/hallway_switch_0"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   unit_of_measurement: "%"
# qos: 1
#   value_template: "{{ value_json.battery|int }}"
#   json_attributes:
#     - "battery"
#     - "voltage"

# - platform: mqtt
#   name: hallway_switch_0_linkquality
#   state_topic: "zigbee2mqtt/hallway_switch_0"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   value_template: "{{ value_json.linkquality|int }}"
#   json_attributes:
#     - "battery"
#     - "voltage"

- platform: mqtt
  name: garage_power_0
  state_topic: "zigbee2mqtt/garage_power_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "Watt"
  qos: 1
  icon: "mdi:flash"
  value_template: "{{ value_json.power|int }}"
  json_attributes:
    - "voltage"
    - "temperature"
    - "consumption"
    - "current"
    - "power_factor"

- platform: mqtt
  name: garage_power_0_linkquality
  state_topic: "zigbee2mqtt/garage_power_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "voltage"

- platform: mqtt
  name: scullery_smoke_0_linkquality
  state_topic: "zigbee2mqtt/scullery_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: scullery_smoke_0_battery
  state_topic: "zigbee2mqtt/scullery_smoke_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: hallway_pir_0_battery
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: hallway_pir_0_linkquality
  state_topic: "zigbee2mqtt/hallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.linkquality }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: upperhallway_pir_0_illuminance
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: upperhallway_pir_0_linkquality
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.linkquality }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: upperhallway_pir_0_battery
  state_topic: "zigbee2mqtt/upperhallway_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: closetroom_pir_0_illuminance
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  qos: 1
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: closetroom_pir_0_linkquality
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.linkquality }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: closetroom_pir_0_battery
  state_topic: "zigbee2mqtt/closetroom_pir_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  qos: 1
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"
