- platform: mqtt
  name: doorbell
  state_topic: "sensor/doorbell"
  icon: mdi:alarm-bell
  expire_after: 60

- platform: template
  sensors:
    last_doorbell:
      entity_id: sensor.doorbell
      value_template: "{{ as_timestamp(states.sensor.doorbell.last_changed)|timestamp_custom('%a %H:%M', True)|default('N/A') }}"
