- platform: mqtt
  name: "Lux Livingroom"
  state_topic: "zstr/livingroom/lux1"
  unit_of_measurement: "lx"
- platform: mqtt
  name: "Temperature Livingroom"
  state_topic: "zstr/livingroom/temp1"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Luchtvochtigheid Livingroom"
  unit_of_measurement: "%"
  state_topic: "zstr/livingroom/humid1"
- platform: mqtt
  name: zigbee2mqtt_status
  state_topic: "zigbee2mqtt/bridge/state"

- platform: mqtt
  name: kitchen_temp_0_temperature
  state_topic: "zigbee2mqtt/kitchen_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:temperature-celsius"
  value_template: "{{ value_json.temperature }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: mqtt
  name: kitchen_temp_0_humidity
  state_topic: "zigbee2mqtt/kitchen_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: mqtt
  name: kitchen_temp_0_battery
  state_topic: "zigbee2mqtt/kitchen_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery|int }}"
  json_attributes:
    - "battery"
    - "voltage"

- platform: mqtt
  name: kitchen_temp_0_linkquality
  state_topic: "zigbee2mqtt/kitchen_temp_0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality|int }}"
  json_attributes:
    - "battery"
    - "voltage"
