- platform: template
  sensors:
    frank_home_direction:
      friendly_name: "Frank richting Home"
      value_template: "{{ state_attr('proximity.frank_home', 'dir_of_travel') }}"
    malissa_home_direction:
      friendly_name: "Malissa richting Home"
      value_template: "{{ state_attr('proximity.malissa_home', 'dir_of_travel') }}"
