- platform: statistics
  name: proximity_frank_home_stats
  entity_id: proximity.frank_home
  max_age:
    minutes: 15
  precision: 0

- platform: statistics
  name: proximity_malissa_home_stats
  entity_id: proximity.malissa_home
  max_age:
    minutes: 15
  precision: 0
