- platform: command_line
  command: "curl -m 10 -G -s -d type=ANDROID -d service=OPHAALSCHEMA -d land=NL -d postcode=$(echo {{ states('input_text.trash_announcement_zipcode') }} ) -d straatId=0 -d huisnr=$(echo {{ states('input_text.trash_announcement_housenumber') }} ) https://dataservice.deafvalapp.nl/dataservice/DataServiceServlet"
  name: trash_today
  scan_interval: 3600
  value_template: >
    {% set data = value.split("\n") %}
    {% set today = as_timestamp(now()) | timestamp_custom("%d-%m-%Y") %}
    {% for row in data %}
      {% set row = row.split(";") %}
      {% if (today in row) %}
        {{ row[0] + ' ' }}
      {% endif %}
    {% endfor %}

- platform: command_line
  command: "curl -m 10 -G -s -d type=ANDROID -d service=OPHAALSCHEMA -d land=NL -d postcode=$(echo {{ states('input_text.trash_announcement_zipcode') }} ) -d straatId=0 -d huisnr=$(echo {{ states('input_text.trash_announcement_housenumber') }} ) https://dataservice.deafvalapp.nl/dataservice/DataServiceServlet"
  name: trash_tomorrow
  scan_interval: 3600
  value_template: >
    {% set data = value.split("\n") %}
    {% set tomorrow = (as_timestamp(now())+86400) | timestamp_custom("%d-%m-%Y") %}
    {% for row in data %}
      {% set row = row.split(";") %}
      {% if (tomorrow in row) %}
        {{ row[0] + ' '}}
      {% endif %}
    {% endfor %}
