- platform: command_line
  command: "curl -m 10 -G -s -d type=ANDROID -d service=OPHAALSCHEMA -d land=NL -d postcode=$(echo {{ states('input_text.trash_announcement_zipcode') }} ) -d straatId=0 -d huisnr=$(echo {{ states('input_text.trash_announcement_housenumber') }} ) https://dataservice.deafvalapp.nl/dataservice/DataServiceServlet"
  name: trash_today
  scan_interval: 3600
  value_template: >
    {% set data = value.split("\n") %}
    {% set today = as_timestamp(now()) | timestamp_custom("%d-%m-%Y") %}
    {% for row in data %}
      {% set row = row.split(";") %}
      {% if (today in row) %}
        {{ row[0] + ' ' }}
      {% endif %}
    {% endfor %}

- platform: command_line
  command: "curl -m 10 -G -s -d type=ANDROID -d service=OPHAALSCHEMA -d land=NL -d postcode=$(echo {{ states('input_text.trash_announcement_zipcode') }} ) -d straatId=0 -d huisnr=$(echo {{ states('input_text.trash_announcement_housenumber') }} ) https://dataservice.deafvalapp.nl/dataservice/DataServiceServlet"
  name: trash_tomorrow
  scan_interval: 3600
  value_template: >
    {% set data = value.split("\n") %}
    {% set tomorrow = (as_timestamp(now())+86400) | timestamp_custom("%d-%m-%Y") %}
    {% for row in data %}
      {% set row = row.split(";") %}
      {% if (tomorrow in row) %}
        {{ row[0] + ' '}}
      {% endif %}
    {% endfor %}

- platform: command_line
  command: "curl -m 10 -G -s -d type=ANDROID -d service=OPHAALSCHEMA -d land=NL -d postcode=$(echo {{ states('input_text.trash_announcement_zipcode') }} ) -d straatId=0 -d huisnr=$(echo {{ states('input_text.trash_announcement_housenumber') }} ) https://dataservice.deafvalapp.nl/dataservice/DataServiceServlet"
  name: trash_gft_nextdate
  scan_interval: 3600
  value_template: >
    {% set data = value.split("\n") %}
    {% set yesterday = strptime(((as_timestamp(now()) - 86400) | timestamp_custom("%d-%m-%Y")), "%d-%m-%Y") %}
    {% set dayInTwoWeeks = strptime(((as_timestamp(now())+ (86400 * 14)) | timestamp_custom("%d-%m-%Y")), "%d-%m-%Y") %} 
    {% for row in data %}
      {% set row = row.split(";") %}
      {% if row[0] == "GFT" %}
        {% for datestr in row %}
          {% if not loop.first and not loop.last %}
            {% set dateobj = strptime(datestr, "%d-%m-%Y") %}
            {% if ((dateobj > yesterday) and (dateobj < dayInTwoWeeks)) %}
              {{ datestr }}
            {% endif %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}

- platform: command_line
  command: "curl -m 10 -G -s -d type=ANDROID -d service=OPHAALSCHEMA -d land=NL -d postcode=$(echo {{ states('input_text.trash_announcement_zipcode') }} ) -d straatId=0 -d huisnr=$(echo {{ states('input_text.trash_announcement_housenumber') }} ) https://dataservice.deafvalapp.nl/dataservice/DataServiceServlet"
  name: trash_rest_nextdate
  scan_interval: 3600
  value_template: >
    {% set data = value.split("\n") %}
    {% set yesterday = strptime(((as_timestamp(now()) - 86400) | timestamp_custom("%d-%m-%Y")), "%d-%m-%Y") %}
    {% set dayInTwoWeeks = strptime(((as_timestamp(now())+ (86400 * 14)) | timestamp_custom("%d-%m-%Y")), "%d-%m-%Y") %} 
    {% for row in data %}
      {% set row = row.split(";") %}
      {% if row[0] == "REST" %}
        {% for datestr in row %}
          {% if not loop.first and not loop.last %}
            {% set dateobj = strptime(datestr, "%d-%m-%Y") %}
            {% if ((dateobj > yesterday) and (dateobj < dayInTwoWeeks)) %}
              {{ datestr }}
            {% endif %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}

- platform: command_line
  command: "curl -m 10 -G -s -d type=ANDROID -d service=OPHAALSCHEMA -d land=NL -d postcode=$(echo {{ states('input_text.trash_announcement_zipcode') }} ) -d straatId=0 -d huisnr=$(echo {{ states('input_text.trash_announcement_housenumber') }} ) https://dataservice.deafvalapp.nl/dataservice/DataServiceServlet"
  name: trash_papier_nextdate
  scan_interval: 3600
  value_template: >
    {% set data = value.split("\n") %}
    {% set yesterday = strptime(((as_timestamp(now()) - 86400) | timestamp_custom("%d-%m-%Y")), "%d-%m-%Y") %}
    {% set dayInTwoWeeks = strptime(((as_timestamp(now())+ (86400 * 14)) | timestamp_custom("%d-%m-%Y")), "%d-%m-%Y") %} 
    {% for row in data %}
      {% set row = row.split(";") %}
      {% if row[0] == "PAPIER" %}
        {% for datestr in row %}
          {% if not loop.first and not loop.last %}
            {% set dateobj = strptime(datestr, "%d-%m-%Y") %}
            {% if ((dateobj > yesterday) and (dateobj < dayInTwoWeeks)) %}
              {{ datestr }}
            {% endif %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}

- platform: command_line
  command: "curl -m 10 -G -s -d type=ANDROID -d service=OPHAALSCHEMA -d land=NL -d postcode=$(echo {{ states('input_text.trash_announcement_zipcode') }} ) -d straatId=0 -d huisnr=$(echo {{ states('input_text.trash_announcement_housenumber') }} ) https://dataservice.deafvalapp.nl/dataservice/DataServiceServlet"
  name: trash_plastic_nextdate
  scan_interval: 3600
  value_template: >
    {% set data = value.split("\n") %}
    {% set yesterday = strptime(((as_timestamp(now()) - 86400) | timestamp_custom("%d-%m-%Y")), "%d-%m-%Y") %}
    {% set dayInTwoWeeks = strptime(((as_timestamp(now())+ (86400 * 14)) | timestamp_custom("%d-%m-%Y")), "%d-%m-%Y") %} 
    {% for row in data %}
      {% set row = row.split(";") %}
      {% if row[0] == "PLASTIC" %}
        {% for datestr in row %}
          {% if not loop.first and not loop.last %}
            {% set dateobj = strptime(datestr, "%d-%m-%Y") %}
            {% if ((dateobj > yesterday) and (dateobj < dayInTwoWeeks)) %}
              {{ datestr }}
            {% endif %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
