- platform: waze_travel_time
  name: waze_frank_to_home
  origin: person.frank
  destination: zone.home
  region: 'EU'

- platform: waze_travel_time
  name: waze_malissa_to_home
  origin: person.malissa
  destination: zone.home
  region: 'EU'

- platform: waze_travel_time
  name: waze_calendar_to_next_appointment
  origin: zone.home
  region: EU
  destination: sensor.calendar_malissa_frank_location

# - platform: waze_travel_time
#   name: waze_frank_work_to_home
#   origin: !secret waze_frank_work_address
#   destination: !secret waze_home_address
#   region: 'EU'

# - platform: waze_travel_time
#   name: waze_frank_home_to_work
#   origin: !secret waze_home_address
#   destination: !secret waze_frank_work_address
#   region: 'EU'

# - platform: waze_travel_time
#   name: waze_frank_work_to_malissa_work
#   origin: !secret waze_frank_work_address
#   destination: !secret waze_malissa_work_address
#   region: 'EU'

# - platform: waze_travel_time
#   name: waze_malissa_home_to_work
#   origin: !secret waze_home_address
#   destination: !secret waze_malissa_work_address
#   region: 'EU'

# - platform: waze_travel_time
#   name: waze_malissa_work_to_home
#   origin: !secret waze_malissa_work_address
#   destination: !secret waze_home_address
#   region: 'EU'
